// standards-catalog.js
// Shared standards + skills language for student summaries and teacher dashboard views.

window.RP_STANDARDS_CATALOG = {
official: {
  "6.P": "DOMAIN: Practices (P) Students engage routinely in four literacy practices that ground, shape, and inform the expectations of the Foundations, Language, and Texts domains.",
  "6.P.EICC": "I. BIG IDEA: Engagement & Intention for Comprehension & Composition Students develop personal and academic identities as readers and writers, approaching texts for a variety of tasks and purposes and engaging in reading and writing processes in order to deepen comprehension and strengthen composition.",
  "6.P.EICC.1": "Reader & Writer Identity Build an identity as a reader and writer, developing a repertoire of resources and tools to continuously expand participation as an active consumer and producer of texts.",
  "6.P.EICC.1.a": "Generate, understand, monitor, and discuss personal and academic reading and writing goals, revising as appropriate. (I/C)",
  "6.P.EICC.1.b": "Discuss or write about personal and academic reading and writing preferences, referring to specific techniques, topics, modes, and genres that resonate most. (I/C)",
  "6.P.EICC.1.c": "Select, read, and write texts of personal interest and academic relevance to grade-level texts and topics. (I/C)",
  "6.P.EICC.1.d": "Build a repertoire of comprehension and composition skills, strategies, and techniques, drawing from them as needed to aid the interpretation and construction of texts. (I/C)",
  "6.P.EICC.1.e": "Participate in a community of readers and writers by developing group norms, discussing texts, sharing individual writing, listening as others share their writing, and offering and responding to feedback. (I/C)",
  "6.P.EICC.1.f": "Develop independence and autonomy as a reader and writer. (I/C)",
  "6.P.EICC.2": "Engagement & Intention Engage in written or spoken dialogue as author and audience for a variety of tasks and purposes, making intentional connections within, between, and beyond texts.",
  "6.P.EICC.2.a": "Share real or imagined experiences by interpreting and constructing texts that tell or include stories. (I/C)",
  "6.P.EICC.2.b": "Make use of texts to build knowledge, develop skills, make informed decisions, and share information and ideas. (I/C)",
  "6.P.EICC.2.c": "Explain and learn concepts and processes by interpreting and constructing texts. (I/C)",
  "6.P.EICC.2.d": "Interpret and construct texts to aid the analysis and evaluation of texts and ideas. (I/C)",
  "6.P.EICC.2.e": "Consume and produce texts in order to solve problems or influence decisions. (I/C)",
  "6.P.EICC.3": "Comprehension Strategies Engage with a range of complex texts for a variety of tasks and purposes, accessing and using strategies for comprehension before, during, and after reading as part of the meaning-making process.",
  "6.P.EICC.3.a": "Establish a purpose and set goals for reading, monitor comprehension, and adjust as needed. (I)",
  "6.P.EICC.3.b": "Scan and skim the text, making note of structures and sections that might be most useful. (I)",
  "6.P.EICC.3.c": "Draw from, compare, build, and integrate prior knowledge with the material in the text, addressing inconsistencies or gaps and adding to knowledge repertoires as appropriate. (I)",
  "6.P.EICC.3.d": "Summarize and visualize sections of the text to maintain understanding. (I)",
  "6.P.EICC.3.e": "Make and track predictions about the events and information likely to come next. (I)",
  "6.P.EICC.3.f": "Make, track, and support inferences about different levels of meaning within the text. (I)",
  "6.P.EICC.3.g": "Determine the meanings of unfamiliar words and concepts by applying knowledge of context and of academic vocabulary and word parts. (I)",
  "6.P.EICC.4": "Writing Processes Compose a range of texts for a variety of purposes and audiences, flexibly engaging in writing processes to plan, draft, evaluate, revise, and edit texts.",
  "6.P.EICC.4.a": "Establish a purpose and goals for writing and identify a target audience. (C)",
  "6.P.EICC.4.b": "Plan how to organize the text by selecting modes, genres, and structures that will achieve the purpose and meet the needs of the target audience. (C)",
  "6.P.EICC.4.c": "Generate ideas for content by assessing prior knowledge, gathering information from texts, and engaging in discussions with others. (C)",
  "6.P.EICC.4.d": "Link ideas and information to the organization plan, highlighting ideas and information that are most relevant, useful, and impactful. (C)",
  "6.P.EICC.4.e": "Construct an initial draft by integrating ideas and information; selecting words, phrases, and sentences; and incorporating craft techniques that will best achieve the purpose of the text and resonate with the target audience. (C)",
  "6.P.EICC.4.f": "Evaluate the text’s effectiveness based on self-review or feedback from others, determining whether the text matches the purpose and goals for writing. (C)",
  "6.P.EICC.4.g": "Make changes to the text based on self-evaluation or external feedback, revising the organization, ideas, information, word choices, and craft techniques in order to increase the text’s effectiveness. (C)",
  "6.P.EICC.4.h": "Edit the text, ensuring it adheres to the conventions of written language. (C)",

  "6.P.ST": "II. BIG IDEA: Situating Texts Students develop and apply a multilayered understanding of context, author, audience, and purpose to ground and propel the interpretation and construction of texts.",
  "6.P.ST.1": "Context Develop and apply knowledge of key components of context such as background information, geographic location, cultural influences, time period, and contemporary events when interpreting and constructing texts.",
  "6.P.ST.1.a": "Use prior knowledge, formal or informal research, and discussions with others to identify the key components of context that are most relevant. (I/C)",
  "6.P.ST.1.b": "Consider how context impacts the purposes of the author and the audience. (I/C)",
  "6.P.ST.1.c": "Explore how context shapes the author’s decisions and the audience’s responses during the interpretation and construction of texts. (I/C)",
  "6.P.ST.2": "Author, Audience, & Purpose Interpret and construct texts by developing and applying knowledge of the strategies and techniques authors use to accommodate the target audience and achieve the text’s purpose.",
  "6.P.ST.2.a": "Develop and apply knowledge of author, audience, and context to discern and establish the purpose of texts being interpreted or constructed and to evaluate the extent to which those texts achieve those purposes. (I/C)",
  "6.P.ST.2.b": "Draw from knowledge of author, audience, and context to discern and establish a clear point of view or unique perspective when interpreting and constructing texts. (I/C)",
  "6.P.ST.2.c": "Draw from knowledge of how authors consider context and audience to determine which information and ideas to highlight, which text design is most accessible, which word choices and language structures are most effective, and which craft techniques are most impactful. (I/C)",

  "6.P.AC": "III. BIG IDEA: Author’s Craft Students apply knowledge of author’s craft to enhance the interpretation and construction of texts.",
  "6.P.AC.1": "Reading like a Writer Interpret texts through the author’s lens by identifying, analyzing, and evaluating craft techniques that are connected to the responses, thoughts, decisions, and questions triggered by the text.",
  "6.P.AC.1.a": "Identify, apply, and analyze the literary, expository, and opinion (grades K-5) or rhetorical (grades 6-12) elements in texts, explaining or evaluating how specific elements affect the target audience and support the text’s purpose. (I/C)",
  "6.P.AC.1.b": "Identify, apply, and analyze important, interesting, or effective uses of language, explaining or evaluating how specific word choices affect the target audience and support the text’s purpose. (I/C)",
  "6.P.AC.1.c": "Explain, analyze, and evaluate how the author’s use of sentence structure and syntax affects the target audience and supports the text’s purpose. (I/C)",
  "6.P.AC.1.d": "Describe, analyze, and evaluate the design and organization of the text, explaining how specific formats, structures, patterns, and features influence the audience, contribute to the text’s accessibility, and support the text’s purpose. (I/C)",
  "6.P.AC.2": "Writing like a Reader Construct texts with the audience’s experience in mind, basing decisions about craft techniques on context and purpose.",
  "6.P.AC.2.a": "Integrate literary, expository, and opinion (grades K-5) or rhetorical (grades 6-12) elements to appeal to target audiences and achieve specific purposes. (I/C)",
  "6.P.AC.2.b": "Craft words and phrases in order to influence the responses, thoughts, decisions, and questions of the target audience and achieve a specific purpose. (I/C)",
  "6.P.AC.2.c": "Make decisions about sentence structure and syntax in order to accommodate and influence the audience and achieve a specific purpose. (I/C)",
  "6.P.AC.2.d": "Organize texts by incorporating specific formats, structures, patterns, and features to influence the audience, facilitate accessibility, and support the text’s purpose. (I/C)",
  "6.P.AC.3": "Text Design Consider the impact of text design on audience and purpose when consuming and producing texts across modes and genres.",
  "6.P.AC.3.a": "Explore and create texts in various modes and genres, developing and applying knowledge of how specific features impact meaning, tone, style, purpose, and audience. (I/C)",
  "6.P.AC.3.b": "Apply knowledge of how mode and genre impact what kinds of ideas and information are included in texts. (I/C)",
  "6.P.AC.3.c": "Apply knowledge of how mode and genre impact how ideas and information are structured and arranged in texts. (I/C)",
  "6.P.AC.3.d": "Consume and produce multimodal texts, integrating a variety of genres, text features, and craft techniques to influence target audiences and achieve specific purposes. (I/C)",

  "6.P.CP": "IV. BIG IDEA: Collaboration & Presentation Students build and share knowledge as they engage with others in a range of settings and for a variety of purposes.",
  "6.P.CP.1": "Collaboration Collaborate with others to accomplish shared goals and projects.",
  "6.P.CP.1.a": "Arrive to group discussions and collaborative meetings prepared to be an active participant in the work. (I/C)",
  "6.P.CP.1.b": "Collaborate with others to determine group norms, establish goals and procedures, and facilitate productivity when working on shared projects. (I/C)",
  "6.P.CP.1.c": "Contribute to discussions and shared projects by offering ideas, listening to the ideas of others, and providing feedback. (I/C)",
  "6.P.CP.1.d": "Work with others to discuss topics, investigate questions, solve problems, and explore and create texts. (I/C)",
  "6.P.CP.2": "Presentation Use presentation skills to tailor communication to target audiences for specific purposes.",
  "6.P.CP.2.a": "Communicate clearly to present ideas, information, and texts. (I/C)",
  "6.P.CP.2.b": "Integrate modes and genres most appropriate to purpose and audience. (I/C)",
  "6.P.CP.2.c": "Vary tone, pace, and nonverbal gestures as appropriate to purpose and audience. (I/C)",
  "6.P.CP.2.d": "Engage in dialogue with audiences by asking and answering questions. (I/C)",
  "6.P.CP.2.e": "Build background knowledge by reciting all or part of significant poems and speeches as appropriate by grade level. (I/C)",

  "6.L": "DOMAIN: Language (L) Students learn and apply the structures and conventions of standard English. Students observe and analyze how grammar works in reading and writing. Students build vocabularies and determine word meanings as they relate to reading and writing.",
  "6.L.GC": "I. BIG IDEA: Grammar Conventions Students observe, analyze, and use the structures and conventions of Standard English grammar, usage, and mechanics as they interpret and construct texts.",
  "6.L.GC.1": "Grammar, Usage, & Mechanics Draw from knowledge of the conventions of Standard English grammar, usage, and mechanics when analyzing and constructing texts.",
  "6.L.GC.1.43": "Grammar: Form and use the progressive, perfect, and perfect progressive verb aspects. (Master)",
  "6.L.GC.1.44": "Grammar: Form and use participles. (Master)",
  "6.L.GC.1.45": "Usage: Recognize and correct vague pronoun references. (Master)",
  "6.L.GC.1.46": "Grammar: Use correlative conjunctions to join words, phrases, or clauses. (Master)",
  "6.L.GC.1.47": "Mechanics: Use conventional capitalization, quotation marks, commas, end punctuation, and attributions to indicate exact words and lines of dialogue. (Master)",
  "6.L.GC.1.48": "Mechanics: Use semicolons to separate items in a series or list when at least one of the items already contains commas. (Master)",
  "6.L.GC.1.49": "Mechanics: Use commas, parentheses, and dashes to set off nonessential words, phrases, or clauses. (Introduce)",
  "6.L.GC.1.50": "Mechanics: Use ellipses appropriately. (Introduce)",
  "6.L.GC.1.51": "Mechanics: Use hyphens with appropriate affixes and compound words. (Introduce)",
  "6.L.GC.1.52": "Mechanics: Use semicolons, with or without a conjunctive adverb, to form compound and compound-complex sentences. (Introduce)",
  "6.L.GC.1.53": "Grammar, Mechanics Use parts of speech and their associated phrases or clauses to perform indicated sentence functions (e.g., subject, direct object, predicate nominative, modifier). (Introduce)",
  "6.L.GC.1.54": "Mechanics: Use conventional capitalization, quotation marks, commas, end punctuation, and parentheses (citations) when incorporating textual evidence. (Continue)",
  "6.L.GC.2": "Syntax Apply understanding of syntax to comprehend, analyze, condense, and combine ideas and information, enhancing clarity, style, and meaning.",
  "6.L.GC.2.a": "Apply understandings of syntax to comprehend and analyze a variety of grade-level texts. (I)",
  "6.L.GC.2.b": "Use a variety of simple, compound, complex, and compound-complex sentences to condense and combine ideas, maintaining consistent verb tense throughout the text. (C)",
  "6.L.GC.2.c": "Identify and use active voice in sentences, revising for subject-verb agreement. (C)",
  "6.L.GC.2.d": "Build and enrich ideas and information in texts, using modifiers when incorporating details and descriptions to convey meaning and facilitate engagement. (C)",

  "6.L.V": "II. BIG IDEA: Vocabulary Students engage in a wide range of written and spoken activities during which they expand and deepen their vocabularies, build word analysis skillsets (morphology), and determine or clarify the meanings of words and phrases.",
  "6.L.V.1": "General, Academic, & Specialized Vocabulary Use a variety of approaches to continuously build vocabulary across a range of real-life, academic, and disciplinary contexts and apply those understandings to analyze texts and to communicate effectively.",
  "6.L.V.1.a": "Acquire a range of general, academic, and disciplinary vocabulary through grade-level print, digital, and/or multimodal texts or content. (I)",
  "6.L.V.1.b": "Use grade-level general, academic, and disciplinary vocabulary to communicate clearly and precisely in a variety of settings. (C)",
  "6.L.V.2": "Word Analysis Use word knowledge and word analysis skills to determine the meaning of unfamiliar words and phrases and to communicate effectively for a variety of purposes.",
  "6.L.V.2.a": "Deconstruct words using etymology knowledge, Greek and Latin roots, root words, and/or affixes to determine or clarify meaning in grade-level texts. (I)",
  "6.L.V.2.b": "Apply knowledge of parts of speech to determine the meanings of words and phrases in grade-level texts. (I)",
  "6.L.V.2.c": "Construct words based on knowledge of Greek and Latin roots, root words, and/or affixes and use those words appropriately in context. (C)",
  "6.L.V.2.d": "Use knowledge of parts of speech to determine precise words and phrases when constructing texts. (C)",
  "6.L.V.3": "Meaning & Purpose Analyze the denotative and connotative meanings of words and phrases and strategically apply those understandings when interpreting and constructing texts.",
  "6.L.V.3.b": "Analyze relationships between words, phrases, and/or clauses (e.g., synonyms, antonyms, analogies, contextual clues) to determine, distinguish, or clarify the meaning of unknown or multiple-meaning words and phrases. (I)",
  "6.L.V.3.c": "Distinguish between the connotations of words that share a similar denotation (e.g., confident, assertive, egotistic, pompous, smug). (I)",
  "6.L.V.3.d": "Use available print and/or digital resources, including reference materials and digital tools (e.g., online search, embedded word processing features), to determine, clarify, or verify the meaning of unknown or multiple-meaning words and phrases. (I)",
  "6.L.V.3.e": "Determine or clarify the nuanced meanings of closely related words or phrases using available print and/or digital resources to make strategic decisions when speaking and writing. (C)",
  "6.T": "DOMAIN: Texts (T) Students grow in their learning as they purposefully engage with texts.",

  "6.T.C": "I. BIG IDEA: Context Students recognize influences on texts and analyze how they shape meaning.",
  "6.T.C.1": "Purpose & Audience Analyze the impact of purpose and audience on a wide variety of texts.",
  "6.T.C.1.a": "Analyze the development of multiple purposes within a single text and how those purposes target specific audiences. (I)",
  "6.T.C.1.b": "Use text mode features to aid comprehension and analysis of a variety of disciplinary texts and their related contexts. (I)",
  "6.T.C.1.c": "Construct multimodal texts and/or presentations for a specific purpose and audience. (C)",
  "6.T.C.2": "Authors & Speakers Analyze how authors’ and/or speakers’ perspectives influence texts and how circumstances shape their creation.",
  "6.T.C.2.a": "Describe and analyze the development and interaction of two or more perspectives conveyed by a single text. (I)",
  "6.T.C.2.b": "Explain how the author’s choice of evidence reveals the author’s perspective and impacts credibility. (I)",
  "6.T.C.2.c": "Identify and analyze the impact of background information and context (e.g., geography, location, era, historical happenings) on text development. (I)",
  "6.T.C.2.d": "Use credible sources to research the answers to questions on academic and individual topics of interest. (C)",

  "6.T.SS": "II. BIG IDEA: Structure & Style Students analyze and use organizational structures and style to shape ideas and information.",
  "6.T.SS.1": "Organization Analyze and use organizational structures to craft meaning.",
  "6.T.SS.1.a": "Explain how authors modify organizational structures or features to convey meaning, respond to the audience, or achieve specific purposes. (I)",
  "6.T.SS.1.b": "Design texts, flexibly employing a variety of text structures and text features to convey information and add style, as appropriate to purpose and audience. (C)",
  "6.T.SS.1.c": "Use concept repetition and connected terms to support transitions, clarify the relationship between ideas and information in texts, and increase text cohesion. (C)",
  "6.T.SS.1.d": "Craft multi-paragraph texts using a coherent structure to organize ideas with an introduction; supporting facts, reasons, details, descriptions, and/or events; and a conclusion. (C)",
  "6.T.SS.2": "Craft Interpret and use language to craft engaging texts.",
  "6.T.SS.2.a": "Determine how figurative and connotative language choices contribute to meaning, mood, or tone in a wide variety of texts. (I)",
  "6.T.SS.2.b": "Use figurative language or literary devices for intentional effects when creating texts to achieve specific purposes or appeal to the target audience. (C)",
  "6.T.SS.2.c": "Compare and contrast characteristics of formal style (e.g., jargon, complete sentences) with those of informal style (e.g., contractions, slang, sentence fragments) and apply understandings to writing and speaking. (C)",

  "6.T.T": "III. BIG IDEA: Techniques Students analyze and apply various techniques to comprehend and shape meaning.",
  "6.T.T.1": "Narrative Techniques Analyze and apply narrative techniques.",
  "6.T.T.1.a": "Describe how narrative techniques are used across the text to develop plot, characters, and setting. (I)",
  "6.T.T.1.b": "Analyze how setting, events, conflict, and characterization influence plot pacing. (I)",
  "6.T.T.1.c": "Identify multiple themes and describe how the relationships and interactions between characters influence and shape themes. (I)",
  "6.T.T.1.d": "Compare and contrast literary texts in different modes and genres in terms of their approaches to similar themes and topics. (I)",
  "6.T.T.1.e": "Apply narrative techniques to enhance writing, engage audiences, and achieve specific purposes. (C)",
  "6.T.T.2": "Expository Techniques Analyze and apply expository techniques.",
  "6.T.T.2.a": "Recognize and describe expository techniques used to present and design content, including main ideas, facts, key details, and a sense of closure. (I)",
  "6.T.T.2.b": "Compare and contrast one author’s presentation of events with that of another on the same historical event or topic. (I)",
  "6.T.T.2.d": "Apply expository techniques (e.g., main idea, facts, key details, sense of closure) to enhance writing and engage audiences. (C)",
  "6.T.T.3": "Argumentative Techniques Analyze and apply argumentative techniques.",
  "6.T.T.3.a": "Recognize and explain argumentative techniques used to present and design content, including an author’s claim, supporting relevant evidence, an identified counterclaim, and a conclusion that logically follows the argument. (I)",
  "6.T.T.3.c": "Apply argumentative techniques (e.g., author’s claim, supporting relevant evidence, an identified counterclaim, and a logical conclusion) to enhance writing and engage audiences. (C)",
  "6.T.T.4": "Poetic Techniques Analyze and apply poetic techniques.",
  "6.T.T.4.a": "Recognize and describe poetic techniques used to present and design content, including stanzas, rhyme scheme, imagery, figurative language, and/or sound devices. (I)",
  "6.T.T.4.b": "Apply poetic techniques (e.g., stanzas, rhyme/rhyme scheme, imagery, figurative language, sound devices) to produce poetry and engage audiences. (C)",

  "6.T.RA": "IV. BIG IDEA: Research & Analysis Students use, discuss, analyze, and curate texts as they engage in various conversations, activities, and projects about a range of grade-level texts and topics.",
  "6.T.RA.1": "Research & Inquiry Conduct research, generating questions to guide investigations of complex topics of interest and using credible sources to support analyses.",
  "6.T.RA.1.a": "Generate questions to guide research and make connections between related topics of interest, formulating questions to investigate complex topics and ideas. (I)",
  "6.T.RA.1.b": "Conduct research by locating, gathering, curating, and integrating information from credible sources (including print, digital, and personal communication) about texts and related topics. (I)",
  "6.T.RA.1.c": "Draw from accumulated knowledge and research to analyze texts, supporting, challenging, or extending ideas and information. (C)",
  "6.T.RA.2": "Curating Sources & Evidence Utilize multiple print and digital texts to address a specific topic or question, assessing source credibility and relevance and integrating evidence properly to avoid plagiarism.",
  "6.T.RA.2.a": "Locate evidence in print and digital sources to support a central idea or question, recording basic bibliographic information, such as author, title, and page number. (I)",
  "6.T.RA.2.b": "Analyze print and digital texts to identify features of credible, relevant sources and to determine indicators that might signal unreliable sources. (I)",
  "6.T.RA.2.c": "Use basic parenthetical citations to credit authors when quoting or paraphrasing texts, ensuring each source is accompanied by a basic entry on a works cited page. (C)",

  "6.T.PM": "V. BIG IDEA: Periods & Movements Students demonstrate knowledge of dominant themes, genres, and verbal styles of literature from a particular time period.",
  "6.T.PM.1": "Periods & Movements Demonstrate knowledge of dominant themes, genres, and verbal styles of literature from a particular time period.",
  "6.T.PM.1.a": "Read and comprehend myths and stories (fictional or historical) that modern writers have adapted into their own works. (I)",
  "6.T.PM.1.b": "Read and comprehend one genre of literature from a particular time period. (I)"
},

studentFriendly: { 
 "6.P": "I can use reading, writing, speaking, and thinking skills to understand and create texts.",
  "6.P.EICC": "I can grow as a reader and writer by reading and writing for different purposes, using strategies, and improving my work.",
  "6.P.EICC.1": "I can build my identity as a reader and writer by using tools, strategies, and resources that help me grow.",
  "6.P.EICC.1.a": "I can set reading and writing goals, check my progress, talk about them, and revise them when needed.",
  "6.P.EICC.1.b": "I can explain my reading and writing preferences using specific examples of topics, genres, techniques, or formats I enjoy.",
  "6.P.EICC.1.c": "I can choose texts to read and write that connect to my interests and school topics.",
  "6.P.EICC.1.d": "I can use different reading and writing strategies when I need help understanding or creating a text.",
  "6.P.EICC.1.e": "I can participate in a reading and writing community by discussing texts, sharing writing, listening to others, and giving or using feedback.",
  "6.P.EICC.1.f": "I can become more independent as a reader and writer.",
  "6.P.EICC.2": "I can read, write, speak, and listen for different purposes while making connections within and beyond texts.",
  "6.P.EICC.2.a": "I can share real or imagined experiences through stories and texts.",
  "6.P.EICC.2.b": "I can use texts to learn information, build skills, make decisions, and share ideas.",
  "6.P.EICC.2.c": "I can use reading and writing to explain and understand concepts or processes.",
  "6.P.EICC.2.d": "I can analyze and evaluate texts and ideas by reading and creating texts.",
  "6.P.EICC.2.e": "I can use texts to solve problems or influence decisions.",
  "6.P.EICC.3": "I can use reading strategies before, during, and after reading to help me understand complex texts.",
  "6.P.EICC.3.a": "I can set a purpose and goals for reading, check my understanding, and adjust when needed.",
  "6.P.EICC.3.b": "I can skim and scan a text to notice sections and structures that may help me.",
  "6.P.EICC.3.c": "I can connect what I already know to what I read and update my thinking when I learn new information.",
  "6.P.EICC.3.d": "I can summarize and visualize parts of a text to help me understand.",
  "6.P.EICC.3.e": "I can make and track predictions about what may happen or come next in a text.",
  "6.P.EICC.3.f": "I can make, track, and support inferences about deeper meanings in a text.",
  "6.P.EICC.3.g": "I can figure out unfamiliar words and ideas by using context, academic vocabulary, and word parts.",
  "6.P.EICC.4": "I can use the writing process to plan, draft, revise, edit, and improve different types of writing.",
  "6.P.EICC.4.a": "I can identify my purpose, goals, and audience before I write.",
  "6.P.EICC.4.b": "I can plan how to organize my writing so it fits my purpose and audience.",
  "6.P.EICC.4.c": "I can generate ideas by thinking about what I know, using texts, and discussing ideas with others.",
  "6.P.EICC.4.d": "I can connect my ideas and information to my writing plan and choose what is most useful and important.",
  "6.P.EICC.4.e": "I can write a first draft by combining ideas, information, word choices, sentences, and craft techniques that fit my purpose and audience.",
  "6.P.EICC.4.f": "I can evaluate my writing using my own review or feedback from others to see if it meets my purpose and goals.",
  "6.P.EICC.4.g": "I can revise my writing by improving organization, ideas, information, word choice, and craft techniques.",
  "6.P.EICC.4.h": "I can edit my writing so it follows the rules of written language.",

  "6.P.ST": "I can understand how context, author, audience, and purpose affect how texts are written and understood.",
  "6.P.ST.1": "I can use my understanding of context (background, culture, time, and place) to better understand and create texts.",
  "6.P.ST.1.a": "I can use what I already know, research, and discussions to figure out the most important parts of the context.",
  "6.P.ST.1.b": "I can explain how context affects what the author wants to say and how the audience understands it.",
  "6.P.ST.1.c": "I can explore how context influences the author’s choices and the audience’s reactions.",
  "6.P.ST.2": "I can understand how authors use strategies to reach their audience and achieve their purpose.",
  "6.P.ST.2.a": "I can use what I know about the author, audience, and context to figure out the purpose of a text and judge how well it works.",
  "6.P.ST.2.b": "I can develop and explain a clear point of view when reading or writing based on my understanding of the author, audience, and context.",
  "6.P.ST.2.c": "I can explain how authors choose ideas, structure, word choice, and techniques to best communicate with their audience.",

  "6.P.AC": "I can understand and use author’s craft to better analyze texts and improve my own writing.",
  "6.P.AC.1": "I can read like a writer by analyzing how authors use craft techniques to affect the reader.",
  "6.P.AC.1.a": "I can identify and analyze text elements and explain how they affect the audience and support the author’s purpose.",
  "6.P.AC.1.b": "I can analyze word choice and explain how it impacts the reader and supports the purpose.",
  "6.P.AC.1.c": "I can analyze sentence structure and explain how it affects the reader and supports the purpose.",
  "6.P.AC.1.d": "I can analyze how a text is organized and designed and explain how it helps the reader understand the text and supports the purpose.",
  "6.P.AC.2": "I can write with my audience in mind by using craft techniques that match my purpose.",
  "6.P.AC.2.a": "I can use different writing elements to connect with my audience and achieve my purpose.",
  "6.P.AC.2.b": "I can choose words and phrases that influence how my audience thinks and responds.",
  "6.P.AC.2.c": "I can choose sentence structures that fit my audience and purpose.",
  "6.P.AC.2.d": "I can organize my writing in a way that helps my audience understand and supports my purpose.",
  "6.P.AC.3": "I can understand how text design, mode, and genre affect meaning, audience, and purpose.",
  "6.P.AC.3.a": "I can explore and create different types of texts and explain how their features affect meaning, tone, and audience.",
  "6.P.AC.3.b": "I can explain how different text types affect what ideas and information are included.",
  "6.P.AC.3.c": "I can explain how different text types affect how ideas are organized.",
  "6.P.AC.3.d": "I can create and analyze texts that combine different formats and features to communicate with an audience and achieve a purpose.",

  "6.P.CP": "I can work with others and present my ideas clearly for different purposes and audiences.",
  "6.P.CP.1": "I can collaborate with others to complete shared goals and projects.",
  "6.P.CP.1.a": "I can come prepared to participate actively in group discussions and work.",
  "6.P.CP.1.b": "I can help create group rules, set goals, and stay productive when working with others.",
  "6.P.CP.1.c": "I can share my ideas, listen to others, and give helpful feedback.",
  "6.P.CP.1.d": "I can work with others to discuss ideas, answer questions, solve problems, and create texts.",
  "6.P.CP.2": "I can present my ideas in ways that fit my audience and purpose.",
  "6.P.CP.2.a": "I can speak clearly to share ideas, information, and texts.",
  "6.P.CP.2.b": "I can choose the best format or type of presentation for my purpose and audience.",
  "6.P.CP.2.c": "I can adjust my tone, pace, and body language to match my purpose and audience.",
  "6.P.CP.2.d": "I can ask and answer questions to engage with my audience.",
  "6.P.CP.2.e": "I can recite parts of important poems or speeches to build my understanding.",

  "6.L": "I can use grammar, vocabulary, and language rules to help me understand texts and improve my writing.",
  "6.L.GC": "I can understand and use grammar rules and writing conventions to read and write clearly.",
  "6.L.GC.1": "I can use grammar, usage, and mechanics correctly when I read and write.",
  "6.L.GC.1.43": "I can use different verb tenses (progressive and perfect) correctly.",
  "6.L.GC.1.44": "I can use participles correctly in sentences.",
  "6.L.GC.1.45": "I can recognize and fix unclear pronoun references.",
  "6.L.GC.1.46": "I can use correlative conjunctions (like either/or, neither/nor) correctly.",
  "6.L.GC.1.47": "I can use correct capitalization, punctuation, and quotation marks when writing dialogue.",
  "6.L.GC.1.48": "I can use semicolons correctly in complex lists.",
  "6.L.GC.1.49": "I can use commas, parentheses, and dashes to add extra information in sentences.",
  "6.L.GC.1.50": "I can use ellipses correctly.",
  "6.L.GC.1.51": "I can use hyphens correctly in compound words.",
  "6.L.GC.1.52": "I can use semicolons to connect related ideas in sentences.",
  "6.L.GC.1.53": "I can use parts of speech correctly to build clear and complete sentences.",
  "6.L.GC.1.54": "I can use correct punctuation and formatting when adding evidence to my writing.",
  "6.L.GC.2": "I can use sentence structure to make my writing clear, detailed, and interesting.",
  "6.L.GC.2.a": "I can use sentence structure to better understand and analyze texts.",
  "6.L.GC.2.b": "I can use different types of sentences to combine ideas and keep verb tense consistent.",
  "6.L.GC.2.c": "I can use active voice and correct subject-verb agreement in my writing.",
  "6.L.GC.2.d": "I can add details and descriptions using modifiers to make my writing clearer and more engaging.",

  "6.L.V": "I can grow my vocabulary by learning new words, understanding how words work, and using them correctly.",
  "6.L.V.1": "I can build and use vocabulary in everyday, academic, and subject-specific situations.",
  "6.L.V.1.a": "I can learn new words from reading, digital texts, and other sources.",
  "6.L.V.1.b": "I can use grade-level vocabulary clearly and correctly when speaking and writing.",
  "6.L.V.2": "I can use word analysis skills to figure out and use unfamiliar words.",
  "6.L.V.2.a": "I can break apart words using roots, prefixes, suffixes, and word origins to understand their meaning.",
  "6.L.V.2.b": "I can use parts of speech to help me understand the meaning of words.",
  "6.L.V.2.c": "I can build new words using roots and affixes and use them correctly in sentences.",
  "6.L.V.2.d": "I can choose precise words by using my knowledge of parts of speech.",
  "6.L.V.3": "I can understand word meanings and choose words carefully to match my purpose.",
  "6.L.V.3.b": "I can use relationships between words (like synonyms, antonyms, and context clues) to figure out meanings.",
  "6.L.V.3.c": "I can explain how words with similar meanings can have different feelings or tones.",
  "6.L.V.3.d": "I can use dictionaries, digital tools, and other resources to find and check word meanings.",
  "6.L.V.3.e": "I can choose the best word by understanding small differences in meaning.",
  "6.T": "I can learn and grow by reading and working with different types of texts.",
  
  "6.T.C": "I can understand how context and different influences shape the meaning of texts.",
  "6.T.C.1": "I can analyze how purpose and audience affect texts.",
  "6.T.C.1.a": "I can explain how a text may have more than one purpose and how those purposes target different audiences.",
  "6.T.C.1.b": "I can use text features to help me understand and analyze different types of texts.",
  "6.T.C.1.c": "I can create presentations or texts for a specific purpose and audience.",
  "6.T.C.2": "I can analyze how authors’ or speakers’ perspectives and situations shape texts.",
  "6.T.C.2.a": "I can explain how multiple perspectives are developed and interact within a text.",
  "6.T.C.2.b": "I can explain how an author’s evidence shows their perspective and affects credibility.",
  "6.T.C.2.c": "I can analyze how background information and context influence a text.",
  "6.T.C.2.d": "I can research answers to questions using credible sources.",

  "6.T.SS": "I can understand and use structure and style to clearly communicate ideas.",
  "6.T.SS.1": "I can analyze and use text structure to organize ideas and create meaning.",
  "6.T.SS.1.a": "I can explain how authors change structure or features to match their purpose and audience.",
  "6.T.SS.1.b": "I can use different text structures and features to organize my ideas and match my purpose.",
  "6.T.SS.1.c": "I can use repetition and connected words to link ideas and make my writing flow clearly.",
  "6.T.SS.1.d": "I can write organized paragraphs with an introduction, supporting details, and a conclusion.",
  "6.T.SS.2": "I can use language and style to make my writing engaging and effective.",
  "6.T.SS.2.a": "I can explain how figurative language and word choice affect meaning, mood, and tone.",
  "6.T.SS.2.b": "I can use figurative language and literary devices to make my writing more effective.",
  "6.T.SS.2.c": "I can compare formal and informal language and use the right style for my purpose and audience.",

   "6.T.T": "I can understand and use different techniques to make meaning when reading and writing.",
  "6.T.T.1": "I can analyze and use narrative techniques to understand and create stories.",
  "6.T.T.1.a": "I can explain how authors use characters, setting, and plot in a story.",
  "6.T.T.1.b": "I can explain how events, conflict, and characters affect the pace of a story.",
  "6.T.T.1.c": "I can identify themes and explain how characters and their actions help develop them.",
  "6.T.T.1.d": "I can compare how different texts approach similar themes or topics.",
  "6.T.T.1.e": "I can use narrative techniques to improve my writing and engage my audience.",
  "6.T.T.2": "I can analyze and use expository techniques to understand and explain information.",
  "6.T.T.2.a": "I can identify main ideas, facts, and details in informational texts.",
  "6.T.T.2.b": "I can compare how different authors present the same topic or event.",
  "6.T.T.2.d": "I can use main ideas, facts, and details to clearly explain information in my writing.",
  "6.T.T.3": "I can analyze and use argumentative techniques to understand and create arguments.",
  "6.T.T.3.a": "I can identify claims, evidence, counterclaims, and conclusions in arguments.",
  "6.T.T.3.c": "I can write arguments using claims, evidence, counterclaims, and clear conclusions.",
  "6.T.T.4": "I can analyze and use poetic techniques to understand and create poetry.",
  "6.T.T.4.a": "I can identify poetic elements like rhyme, imagery, and figurative language.",
  "6.T.T.4.b": "I can use poetic techniques to create my own poems.",

  "6.T.RA": "I can research, analyze, and use information from texts to learn about topics and support my ideas.",
  "6.T.RA.1": "I can ask questions and conduct research to learn about complex topics.",
  "6.T.RA.1.a": "I can create questions to guide my research and explore connections between topics.",
  "6.T.RA.1.b": "I can gather and organize information from reliable sources, including books, websites, and conversations.",
  "6.T.RA.1.c": "I can use what I’ve learned from research to analyze texts and support or challenge ideas.",
  "6.T.RA.2": "I can find, evaluate, and use sources and evidence responsibly.",
  "6.T.RA.2.a": "I can find evidence in sources and record important information like the author and title.",
  "6.T.RA.2.b": "I can tell if a source is trustworthy and relevant.",
  "6.T.RA.2.c": "I can give credit to sources by using citations and avoiding plagiarism.",

  "6.T.PM": "I can understand how literature reflects different time periods, themes, and styles.",
  "6.T.PM.1": "I can learn about themes, genres, and styles from different time periods.",
  "6.T.PM.1.a": "I can read and understand myths and stories that modern authors have adapted.",
  "6.T.PM.1.b": "I can read and understand a type of literature from a specific time period."
},


  practiceSkills: {
    "central-idea": "I can find the central idea or main message of a text.",
    "summarizing": "I can summarize the most important ideas without adding extra details.",
    "details": "I can use important details to understand and explain a text.",
    "text-evidence": "I can choose evidence from the text to support my answer.",
    "claim": "I can identify the main claim or argument an author is making.",
    "reason": "I can identify reasons that support a claim.",
    "evidence": "I can connect evidence to a claim or reason.",
    "argument-structure": "I can understand how claims, reasons, and evidence work together.",
    "author-opinion": "I can identify what the author thinks or believes.",
    "author-meaning": "I can explain what the author means by specific words or ideas.",
    "text-structure": "I can recognize how a text is organized.",
    "cause-effect": "I can explain how one event or idea causes another.",
    "fact-opinion": "I can tell the difference between facts and opinions.",
    "inference": "I can make an inference using clues from the text.",
    "synthesize": "I can combine information from more than one place to form an answer.",
    "critical-thinking": "I can think carefully about ideas and choose the strongest answer."
  },

  hiddenSkillTags: [
    "mcq",
    "multi-select",
    "matching",
    "highlight",
    "dropdown",
    "drag-drop",
    "video-media",
    "audio-media",
    "passage-1",
    "passage-2",
    "personalization"
  ],

  getOfficialText(code) {
    return this.official[code] || "";
  },

  getStudentText(codeOrSkill) {
    return (
      this.studentFriendly[codeOrSkill] ||
      this.practiceSkills[codeOrSkill] ||
      "I can keep practicing this reading skill."
    );
  },

  shouldShowSkill(skill) {
    return skill && !this.hiddenSkillTags.includes(skill);
  },

  formatSkillLabel(skill) {
    if (/^6\./.test(skill)) return skill;

    return String(skill)
      .split("-")
      .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
      .join(" ");
  }
};