// standards-catalog.js
// Shared standards + skills language for student summaries and teacher dashboard views.

window.RP_STANDARDS_CATALOG = {
official: {
 "7.P": "DOMAIN: Practices (P) Students engage routinely in four literacy practices that ground, shape, and inform the expectations of the Foundations, Language, and Texts domains.",
  "7.P.EICC": "I. BIG IDEA: Engagement & Intention for Comprehension & Composition Students develop personal and academic identities as readers and writers, approaching texts for a variety of tasks and purposes and engaging in reading and writing processes in order to deepen comprehension and strengthen composition.",
  "7.P.EICC.1": "Reader & Writer Identity Build an identity as a reader and writer, developing a repertoire of resources and tools to continuously expand participation as an active consumer and producer of texts.",
  "7.P.EICC.1.a": "Generate, understand, monitor, and discuss personal and academic reading and writing goals, revising as appropriate. (I/C)",
  "7.P.EICC.1.b": "Discuss or write about personal and academic reading and writing preferences, referring to specific techniques, topics, modes, and genres that resonate most. (I/C)",
  "7.P.EICC.1.c": "Select, read, and write texts of personal interest and academic relevance to grade-level texts and topics. (I/C)",
  "7.P.EICC.1.d": "Build a repertoire of comprehension and composition skills, strategies, and techniques, drawing from them as needed to aid the interpretation and construction of texts. (I/C)",
  "7.P.EICC.1.e": "Participate in a community of readers and writers by developing group norms, discussing texts, sharing individual writing, listening as others share their writing, and offering and responding to feedback. (I/C)",
  "7.P.EICC.1.f": "Develop independence and autonomy as a reader and writer. (I/C)",
  "7.P.EICC.2": "Engagement & Intention Engage in written or spoken dialogue as author and audience for a variety of tasks and purposes, making intentional connections within, between, and beyond texts.",
  "7.P.EICC.2.a": "Share real or imagined experiences by interpreting and constructing texts that tell or include stories. (I/C)",
  "7.P.EICC.2.b": "Make use of texts to build knowledge, develop skills, make informed decisions, and share information and ideas. (I/C)",
  "7.P.EICC.2.c": "Explain and learn concepts and processes by interpreting and constructing texts. (I/C)",
  "7.P.EICC.2.d": "Interpret and construct texts to aid the analysis and evaluation of texts and ideas. (I/C)",
  "7.P.EICC.2.e": "Consume and produce texts in order to solve problems or influence decisions. (I/C)",
  "7.P.EICC.3": "Comprehension Strategies Engage with a range of complex texts for a variety of tasks and purposes, accessing and using strategies for comprehension* before, during, and after reading as part of the meaning-making process.",
  "7.P.EICC.3.a": "Establish a purpose and set goals for reading, monitor comprehension, and adjust as needed. (I)",
  "7.P.EICC.3.b": "Scan and skim the text, making note of structures and sections that might be most useful. (I)",
  "7.P.EICC.3.c": "Draw from, compare, build, and integrate prior knowledge with the material in the text, addressing inconsistencies or gaps and adding to knowledge repertoires as appropriate. (I)",
  "7.P.EICC.3.d": "Summarize and visualize sections of the text to maintain understanding. (I)",
  "7.P.EICC.3.e": "Make and track predictions about the events and information likely to come next. (I)",
  "7.P.EICC.3.f": "Make, track, and support inferences about different levels of meaning within the text. (I)",
  "7.P.EICC.3.g": "Determine the meanings of unfamiliar words and concepts by applying knowledge of context and of academic vocabulary and word parts. (I)",
  "7.P.EICC.4": "Writing Processes Compose a range of texts for a variety of purposes and audiences, flexibly engaging in writing processes to plan, draft, evaluate, revise, and edit texts.",
  "7.P.EICC.4.a": "Establish a purpose and goals for writing and identify a target audience. (C)",
  "7.P.EICC.4.b": "Plan how to organize the text by selecting modes, genres, and structures that will achieve the purpose and meet the needs of the target audience. (C)",
  "7.P.EICC.4.c": "Generate ideas for content by assessing prior knowledge, gathering information from texts, and engaging in discussions with others. (C)",
  "7.P.EICC.4.d": "Link ideas and information to the organization plan, highlighting ideas and information that are most relevant, useful, and impactful. (C)",
  "7.P.EICC.4.e": "Construct an initial draft by integrating ideas and information; selecting words, phrases, and sentences; and incorporating craft techniques that will best achieve the purpose of the text and resonate with the target audience. (C)",
  "7.P.EICC.4.f": "Evaluate the text’s effectiveness based on self-review or feedback from others, determining whether the text matches the purpose and goals for writing. (C)",
  "7.P.EICC.4.g": "Make changes to the text based on self-evaluation or external feedback, revising the organization, ideas, information, word choices, and craft techniques in order to increase the text’s effectiveness. (C)",
  "7.P.EICC.4.h": "Edit the text, ensuring it adheres to the conventions of written language. (C)",
  
  "7.P.ST": "II. BIG IDEA: Situating Texts Students develop and apply a multilayered understanding of context, author, audience, and purpose to ground and propel the interpretation and construction of texts.",
  "7.P.ST.1": "Context Develop and apply knowledge of key components of context such as background information, geographic location, cultural influences, time period, and contemporary events when interpreting and constructing texts.",
  "7.P.ST.1.a": "Use prior knowledge, formal or informal research, and discussions with others to identify the key components of context that are most relevant. (I/C)",
  "7.P.ST.1.b": "Consider how context impacts the purposes of the author and the audience. (I/C)",
  "7.P.ST.1.c": "Explore how context shapes the author’s decisions and the audience’s responses during the interpretation and construction of texts. (I/C)",
  "7.P.ST.2": "Author, Audience, & Purpose Interpret and construct texts by developing and applying knowledge of the strategies and techniques authors use to accommodate the target audience and achieve the text’s purpose.",
  "7.P.ST.2.a": "Develop and apply knowledge of author, audience, and context to discern and establish the purpose of texts being interpreted or constructed and to evaluate the extent to which those texts achieve those purposes. (I/C)",
  "7.P.ST.2.b": "Draw from knowledge of author, audience, and context to discern and establish a clear point of view or unique perspective when interpreting and constructing texts. (I/C)",
  "7.P.ST.2.c": "Draw from knowledge of how authors consider context and audience to determine which information and ideas to highlight, which text design is most accessible, which word choices and language structures are most effective, and which craft techniques are most impactful. (I/C)",

  "7.P.AC": "III. BIG IDEA: Author’s Craft Students apply knowledge of author’s craft to enhance the interpretation and construction of texts.",
  "7.P.AC.1": "Reading like a Writer Interpret texts through the author’s lens by identifying, analyzing, and evaluating craft techniques that are connected to the responses, thoughts, decisions, and questions triggered by the text.",
  "7.P.AC.1.a": "Identify, apply, and analyze the literary, expository, and opinion (grades K-5) or rhetorical (grades 6-12) elements in texts, explaining or evaluating how specific elements affect the target audience and support the text’s purpose. (I/C)",
  "7.P.AC.1.b": "Identify, apply, and analyze important, interesting, or effective uses of language, explaining or evaluating how specific word choices affect the target audience and support the text’s purpose. (I/C)",
  "7.P.AC.1.c": "Explain, analyze, and evaluate how the author’s use of sentence structure and syntax affects the target audience and supports the text’s purpose. (I/C)",
  "7.P.AC.1.d": "Describe, analyze, and evaluate the design and organization of the text, explaining how specific formats, structures, patterns, and features influence the audience, contribute to the text’s accessibility, and support the text’s purpose. (I/C)",
  "7.P.AC.2": "Writing like a Reader Construct texts with the audience’s experience in mind, basing decisions about craft techniques on context and purpose.",
  "7.P.AC.2.a": "Integrate literary, expository, and opinion (grades K-5) or rhetorical (grades 6-12) elements to appeal to target audiences and achieve specific purposes. (I/C)",
  "7.P.AC.2.b": "Craft words and phrases in order to influence the responses, thoughts, decisions, and questions of the target audience and achieve a specific purpose. (I/C)",
  "7.P.AC.2.c": "Make decisions about sentence structure and syntax in order to accommodate and influence the audience and achieve a specific purpose. (I/C)",
  "7.P.AC.2.d": "Organize texts by incorporating specific formats, structures, patterns, and features to influence the audience, facilitate accessibility, and support the text’s purpose. (I/C)",
  "7.P.AC.3": "Text Design Consider the impact of text design on audience and purpose when consuming and producing texts across modes and genres",
  "7.P.AC.3.a": "Explore and create texts in various modes and genres, developing and applying knowledge of how specific features impact meaning, tone, style, purpose, and audience. (I/C)",
  "7.P.AC.3.b": "Apply knowledge of how mode and genre impact what kinds of ideas and information are included in texts. (I/C)",
  "7.P.AC.3.c": "Apply knowledge of how mode and genre impact how ideas and information are structured and arranged in texts. (I/C)",
  "7.P.AC.3.d": "Consume and produce multimodal texts, integrating a variety of genres, text features, and craft techniques to influence target audiences and achieve specific purposes. (I/C)",

  "7.P.CP": "IV. BIG IDEA: Collaboration & Presentation Students build and share knowledge as they engage with others in a range of settings and for a variety of purposes.",
  "7.P.CP.1": "Collaboration Collaborate with others to accomplish shared goals and projects",
  "7.P.CP.1.a": "Arrive to group discussions and collaborative meetings prepared to be an active participant in the work. (I/C)",
  "7.P.CP.1.b": "Collaborate with others to determine group norms, establish goals and procedures, and facilitate productivity when working on shared projects. (I/C)",
  "7.P.CP.1.c": "Contribute to discussions and shared projects by offering ideas, listening to the ideas of others, and providing feedback. (I/C)",
  "7.P.CP.1.d": "Work with others to discuss topics, investigate questions, solve problems, and explore and create texts. (I/C)",
  "7.P.CP.2": "Presentation Use presentation skills to tailor communication to target audiences for specific purposes.",
  "7.P.CP.2.a": "Communicate clearly to present ideas, information, and texts. (I/C)",
  "7.P.CP.2.b": "Integrate modes and genres most appropriate to purpose and audience. (I/C)",
  "7.P.CP.2.c": "Vary tone, pace, and nonverbal gestures as appropriate to purpose and audience. (I/C)",
  "7.P.CP.2.d": "Engage in dialogue with audiences by asking and answering questions. (I/C)",
  "7.P.CP.2.e": "Build background knowledge by reciting all or part of significant poems and speeches as appropriate by grade level. (I/C)",

  "7.L": "DOMAIN: Language (L) Students learn and apply the structures and conventions of standard English. Students observe and analyze how grammar works in reading and writing. Students build vocabularies and determine word meanings as they relate to reading and writing.",
  "7.L.GC": "I. BIG IDEA: Grammar Conventions Students observe, analyze, and use the structures and conventions of Standard English grammar, usage, and mechanics as they interpret and construct texts.",
  "7.L.GC.1": "Grammar, Usage, & Mechanics Draw from knowledge of the conventions of Standard English grammar, usage, and mechanics when analyzing and constructing texts.",
  "7.L.GC.1.49": "Mechanics: Use commas, parentheses, and dashes to set off nonessential words, phrases, or clauses. (Master)",
  "7.L.GC.1.50": "Mechanics: Use ellipses appropriately. (Continue)",
  "7.L.GC.1.51": "Mechanics: Use hyphens with appropriate affixes and compound words. (Continue)",
  "7.L.GC.1.52": "Mechanics: Use semicolons, with or without a conjunctive adverb, to form compound and compound-complex sentences. (Continue)",
  "7.L.GC.1.53": "Grammar, Mechanics Use parts of speech and their associated phrases or clauses to perform indicated sentence functions (e.g., subject, direct object, predicate nominative, modifier). (Continue)",
  "7.L.GC.1.54": "Mechanics: Use conventional capitalization, quotation marks, commas, end punctuation, and parentheses (citations) when incorporating textual evidence. (Continue)",
  "7.L.GC.1.55": "Grammar: Use demonstrative pronouns. (Introduce, Master)",
  "7.L.GC.1.56": "Mechanics: Use colons to introduce lists, examples, and explanations. (Introduce)",
  "7.L.GC.1.57": "Usage: Form and use verbals and verbal phrases (participles/participials, gerunds, and infinitives) based on function. (Introduce)",
  "7.L.GC.2": "Syntax Apply understanding of syntax to comprehend, analyze, condense, and combine ideas and information, enhancing clarity, style, and meaning.",
  "7.L.GC.2.a": "Apply understandings of syntax to comprehend and analyze a variety of grade-level texts. (I)",
  "7.L.GC.2.b": "Use a variety of simple, compound, complex, and compound-complex sentences to condense and combine ideas, maintaining consistent verb tense throughout the text. (C)",
  "7.L.GC.2.c": "Distinguish between active and passive voice, revising texts to maintain consistency in active voice. (C)",
  "7.L.GC.2.d": "Build and enrich ideas and information in texts, avoiding misplaced or dangling modifiers when incorporating details and descriptions to convey meaning and facilitate engagement. (C)",
  "7.L.GC.2.e": "This progression begins in 9th grade.",

  "7.L.V": "II. BIG IDEA: Vocabulary Students engage in a wide range of written and spoken activities during which they expand and deepen their vocabularies, build word analysis skillsets (morphology), and determine or clarify the meanings of words and phrases.",
  "7.L.V.1": "General, Academic, & Specialized Vocabulary Use a variety of approaches to continuously build vocabulary across a range of real-life, academic, and disciplinary contexts and apply those understandings to analyze texts and to communicate effectively.",
  "7.L.V.1.a": "Acquire a range of general, academic, and disciplinary vocabulary through grade-level print, digital, and/or multimodal texts or content. (I)",
  "7.L.V.1.b": "Use grade-level general, academic, and disciplinary vocabulary to communicate clearly and precisely in a variety of settings. (C)",
  "7.L.V.2": "Word Analysis Use word knowledge and word analysis skills to determine the meaning of unfamiliar words and phrases and to communicate effectively for a variety of purposes.",
  "7.L.V.2.a": "Deconstruct words using etymology knowledge, Greek and Latin roots, root words, and/or affixes to determine or clarify meaning in grade-level texts. (I)",
  "7.L.V.2.b": "Apply knowledge of parts of speech to determine the meanings of words and phrases in grade-level texts. (I)",
  "7.L.V.2.c": "Construct words based on knowledge of Greek and Latin roots, root words, and/or affixes and use those words appropriately in context. (C)",
  "7.L.V.2.d": "Use knowledge of parts of speech to determine precise words and phrases when constructing texts. (C)",
  "7.L.V.3": "Meaning & Purpose Analyze the denotative and connotative meanings of words and phrases and strategically apply those understandings when interpreting and constructing texts.",
  "7.L.V.3.a": "This progression transitions to 6-8.L.V.3.b.",
  "7.L.V.3.b": "Analyze relationships between words, phrases, and/or clauses (e.g., synonyms, antonyms, analogies, contextual clues) to determine, distinguish, or clarify the meaning of unknown or multiple-meaning words and phrases. (I)",
  "7.L.V.3.c": "Distinguish between the connotations of words that share a similar denotation (e.g., confident, assertive, egotistic, pompous, smug). (I)",
  "7.L.V.3.d": "Use available print and/or digital resources, including reference materials and digital tools (e.g., online search, embedded word processing features), to determine, clarify, or verify the meaning of unknown or multiple-meaning words and phrases. (I)",
  "7.L.V.3.e": "Determine or clarify the nuanced meanings of closely related words or phrases using available print and/or digital resources to make strategic decisions when speaking and writing. (C)",

  "7.T": "DOMAIN: Texts (T) Students grow in their learning as they purposefully engage with texts.",
  "7.T.C": "I. BIG IDEA: Context Students recognize influences on texts and analyze how they shape meaning.",
  "7.T.C.1": "Purpose & Audience Analyze the impact of purpose and audience on a wide variety of texts.",
  "7.T.C.1.a": "Analyze the development of multiple purposes within a single text and how those purposes target specific audiences. (I)",
  "7.T.C.1.b": "Use text mode features to aid comprehension and analysis of a variety of disciplinary texts and their related contexts. (I)",
  "7.T.C.1.c": "Construct multimodal texts and/or presentations for a specific purpose and audience, using multiple, clearly identifiable features of incorporated modes. (C)",
  "7.T.C.2": "Authors & Speakers Analyze how authors’ and/or speakers’ perspectives influence texts and how circumstances shape their creation.",
  "7.T.C.2.a": "Determine the prevailing perspective in a text and analyze how the author distinguishes or corroborates that position. (I)",
  "7.T.C.2.b": "Analyze how evidence and tone reveal the author’s perspective and impact credibility. (I)",
  "7.T.C.2.c": "Analyze the impact of background information and context (e.g., geography, location, era, historical happenings) on text development. (I)",
  "7.T.C.2.d": "Use credible sources to research the answers to questions on academic and individual topics of interest. (C)",

  "7.T.SS": "II. BIG IDEA: Structure & Style Students analyze and use organizational structures and style to shape ideas and information.",
  "7.T.SS.1": "Organization Analyze and use organizational structures to craft meaning.",
  "7.T.SS.1.a": "Analyze how authors modify organizational structures or features to convey meaning, respond to the audience, or achieve specific purposes. (I)",
  "7.T.SS.1.b": "Design texts, flexibly employing a variety of text structures and text features to convey information and add style, as appropriate to purpose and audience. (C)",
  "7.T.SS.1.c": "Use varied transition words and phrases to connect ideas, sentences, paragraphs, and sections of text. (C)",
  "7.T.SS.1.d": "Craft multi-paragraph texts using a coherent structure with an introduction that guides the focus; supporting facts, reasons, details, descriptions, and/or events; and a conclusion. (C)",
  "7.T.SS.2": "Craft Interpret and use language to craft engaging texts.",
  "7.T.SS.2.a": "Explain how figurative language, connotative language, and/or literary device choices contribute to meaning, mood, or tone in a wide variety of texts. (I)",
  "7.T.SS.2.b": "Use figurative language, literary devices, or connotative language for intentional effects when creating texts to achieve specific purposes or appeal to the target audience. (C)",
  "7.T.SS.2.c": "Determine situational use for formal or informal style and apply that determination to choices when writing or speaking. (C)",

  "7.T.T": "III. BIG IDEA: Techniques Students analyze and apply various techniques to comprehend and shape meaning.",
  "7.T.T.1": "Narrative Techniques Analyze and apply narrative techniques.",
  "7.T.T.1.a": "Analyze how narrative techniques are used across the text to develop plot, characters, and setting. (I)",
  "7.T.T.1.b": "Analyze the use of plot structures, conflict, and narrative devices (e.g., flashback, foreshadowing) within a text. (I)",
  "7.T.T.1.c": "Compare and contrast how themes are developed and expressed in texts through characters, events, and plot structure. (I)",
  "7.T.T.1.d": "Compare and contrast a fictional portrayal of a time, place, or character with a historical account of the same period. (I)",
  "7.T.T.1.e": "Apply narrative techniques to enhance writing, engage audiences, and achieve specific purposes. (C)",
  "7.T.T.2": "Expository Techniques Analyze and apply expository techniques.",
  "7.T.T.2.a": "Analyze expository techniques used to present and design content, including main ideas, facts, statistics, key details, information from text features, and a sense of closure. (I)",
  "7.T.T.2.b": "Analyze how two or more authors writing about the same topic shape their presentations of key information by emphasizing different evidence or advancing different interpretations of facts. (I)",
  "7.T.T.2.c": "This progression ends in 5th grade.",
  "7.T.T.2.d": "Apply expository techniques (e.g., main idea, facts, statistics, key details, text features, sense of closure) to enhance writing and engage audiences. (C)",
  "7.T.T.3": "Argumentative Techniques Analyze and apply argumentative techniques.",
  "7.T.T.3.a": "Analyze argumentative techniques used to present and design content, including an author’s claim, supporting relevant evidence, an identified counterclaim, and a conclusion that logically follows the argument. (I)",
  "7.T.T.3.b": "This progression begins in 9th grade.",
  "7.T.T.3.c": "Apply argumentative techniques (e.g., author’s claim, supporting relevant evidence, an identified counterclaim, and a logical conclusion) to enhance writing and engage audiences. (C)",
  "7.T.T.3.d": "This progression begins in 9th grade.",
  "7.T.T.4": "Poetic Techniques Analyze and apply poetic techniques.",
  "7.T.T.4.a": "Analyze poetic techniques used to present and design content, including stanzas, rhyme scheme, imagery, figurative language, and/or sound devices. (I)",
  "7.T.T.4.b": "Apply poetic techniques (e.g., stanzas, rhyme/rhyme scheme, imagery, figurative language, sound devices) to produce poetry and engage audiences. (C)",

  "7.T.RA": "IV. BIG IDEA: Research & Analysis Students use, discuss, analyze, and curate texts as they engage in various conversations, activities, and projects about a range of grade-level texts and topics.",
  "7.T.RA.1": "Research & Inquiry Conduct research, generating questions to guide investigations of complex topics of interest and using credible sources to support analyses.",
  "7.T.RA.1.a": "Generate questions to guide research and make connections between related topics of interest, formulating questions to investigate complex topics and ideas. (I)",
  "7.T.RA.1.b": "Conduct research by locating, gathering, curating, and integrating information from credible sources (including print, digital, and personal communication) about texts and related topics. (C)",
  "7.T.RA.1.c": "Draw from accumulated knowledge and research to analyze texts, supporting, challenging, or extending ideas and information. (C)",
  "7.T.RA.2": "Curating Sources & Evidence Utilize multiple print and digital texts to address a specific topic or question, assessing source credibility and relevance and integrating evidence properly to avoid plagiarism.",
  "7.T.RA.2.a": "Locate evidence in print and digital sources to support a central idea or question, recording standard bibliographic information, such as author, title, website name, page number, and year of publication. (I)",
  "7.T.RA.2.b": "Analyze print and digital texts for credibility and relevance, determining whether the ideas and information support the topic under investigation. (I)",
  "7.T.RA.2.c": "Follow a standard format for citation when integrating textual evidence, clearly identifying and citing the ideas and information of others and ensuring each source is accompanied by a standard entry on a works cited page. (C)",
  
  "7.T.PM": "V. BIG IDEA: Periods & Movements Students demonstrate knowledge of dominant themes, genres, and verbal styles of literature from a particular time period.",
  "7.T.PM.1": "Periods & Movements Demonstrate knowledge of dominant themes, genres, and verbal styles of literature from a particular time period.",
  "7.T.PM.1.a": "Read and comprehend to analyze myths and stories (fictional or historical) that modern writers have adapted into their own works and identify key features of style and theme. (I)",
  "7.T.PM.1.b": "Read and comprehend to analyze one genre of literature from a particular time period and identify key features of style and theme. (I)",
},

studentFriendly: {
  "7.P": "I can use reading, writing, speaking, and thinking skills to understand and create texts.",
  "7.P.EICC": "I can grow as a reader and writer by reading and writing for different purposes, using strategies, and improving my work.",
  "7.P.EICC.1": "I can build my identity as a reader and writer by using tools, strategies, and resources that help me grow.",
  "7.P.EICC.1.a": "I can set reading and writing goals, check my progress, talk about them, and revise them when needed.",
  "7.P.EICC.1.b": "I can explain my reading and writing preferences using specific examples of topics, genres, techniques, or formats I enjoy.",
  "7.P.EICC.1.c": "I can choose texts to read and write that connect to my interests and school topics.",
  "7.P.EICC.1.d": "I can use different reading and writing strategies when I need help understanding or creating a text.",
  "7.P.EICC.1.e": "I can participate in a reading and writing community by discussing texts, sharing writing, listening to others, and giving or using feedback.",
  "7.P.EICC.1.f": "I can become more independent as a reader and writer.",
  "7.P.EICC.2": "I can read, write, speak, and listen for different purposes while making connections within and beyond texts.",
  "7.P.EICC.2.a": "I can share real or imagined experiences through stories and texts.",
  "7.P.EICC.2.b": "I can use texts to learn information, build skills, make decisions, and share ideas.",
  "7.P.EICC.2.c": "I can use reading and writing to explain and understand concepts or processes.",
  "7.P.EICC.2.d": "I can analyze and evaluate texts and ideas by reading and creating texts.",
  "7.P.EICC.2.e": "I can use texts to solve problems or influence decisions.",
  "7.P.EICC.3": "I can use reading strategies before, during, and after reading to help me understand complex texts.",
  "7.P.EICC.3.a": "I can set a purpose and goals for reading, check my understanding, and adjust when needed.",
  "7.P.EICC.3.b": "I can skim and scan a text to notice sections and structures that may help me.",
  "7.P.EICC.3.c": "I can connect what I already know to what I read, compare ideas, and update my thinking when I learn new information.",
  "7.P.EICC.3.d": "I can summarize and visualize parts of a text to help me understand.",
  "7.P.EICC.3.e": "I can make and track predictions about what may happen or come next in a text.",
  "7.P.EICC.3.f": "I can make, track, and support inferences about deeper meanings in a text.",
  "7.P.EICC.3.g": "I can figure out unfamiliar words and ideas by using context, academic vocabulary, and word parts.",
  "7.P.EICC.4": "I can use the writing process to plan, draft, revise, edit, and improve different types of writing.",
  "7.P.EICC.4.a": "I can identify my purpose, goals, and audience before I write.",
  "7.P.EICC.4.b": "I can plan how to organize my writing so it fits my purpose and audience.",
  "7.P.EICC.4.c": "I can generate ideas by thinking about what I know, using texts, and discussing ideas with others.",
  "7.P.EICC.4.d": "I can connect my ideas and information to my writing plan and choose what is most useful and important.",
  "7.P.EICC.4.e": "I can write a first draft by combining ideas, information, word choices, sentences, and craft techniques that fit my purpose and audience.",
  "7.P.EICC.4.f": "I can evaluate my writing using my own review or feedback from others to see if it meets my purpose and goals.",
  "7.P.EICC.4.g": "I can revise my writing by improving organization, ideas, information, word choice, and craft techniques.",
  "7.P.EICC.4.h": "I can edit my writing so it follows the rules of written language.",
  
  "7.P.ST": "I can understand how context, author, audience, and purpose affect how texts are written and understood.",
  "7.P.ST.1": "I can use my understanding of context, such as background, culture, time, and place, to better understand and create texts.",
  "7.P.ST.1.a": "I can use what I already know, research, and discussions to figure out the most important parts of the context.",
  "7.P.ST.1.b": "I can explain how context affects what the author wants to say and how the audience understands it.",
  "7.P.ST.1.c": "I can explore how context influences the author’s choices and the audience’s reactions.",
  "7.P.ST.2": "I can understand how authors use strategies to reach their audience and achieve their purpose.",
  "7.P.ST.2.a": "I can use what I know about the author, audience, and context to figure out the purpose of a text and judge how well it works.",
  "7.P.ST.2.b": "I can use what I know about the author, audience, and context to understand or create a clear point of view.",
  "7.P.ST.2.c": "I can explain how authors choose ideas, structure, word choice, language, and craft techniques to best communicate with their audience.",
  
  "7.P.AC": "I can understand and use author’s craft to better analyze texts and improve my own writing.",
  "7.P.AC.1": "I can read like a writer by analyzing how authors use craft techniques to affect the reader.",
  "7.P.AC.1.a": "I can identify and analyze text elements and explain how they affect the audience and support the author’s purpose.",
  "7.P.AC.1.b": "I can analyze word choice and explain how it impacts the reader and supports the purpose.",
  "7.P.AC.1.c": "I can analyze sentence structure and explain how it affects the reader and supports the purpose.",
  "7.P.AC.1.d": "I can analyze how a text is organized and designed and explain how it helps the reader understand the text and supports the purpose.",
  "7.P.AC.2": "I can write with my audience in mind by using craft techniques that match my purpose.",
  "7.P.AC.2.a": "I can use different writing elements to connect with my audience and achieve my purpose.",
  "7.P.AC.2.b": "I can choose words and phrases that influence how my audience thinks and responds.",
  "7.P.AC.2.c": "I can choose sentence structures that fit my audience and purpose.",
  "7.P.AC.2.d": "I can organize my writing in a way that helps my audience understand and supports my purpose.",
  "7.P.AC.3": "I can understand how text design, mode, and genre affect meaning, audience, and purpose.",
  "7.P.AC.3.a": "I can explore and create different types of texts and explain how their features affect meaning, tone, style, purpose, and audience.",
  "7.P.AC.3.b": "I can explain how different text types affect what ideas and information are included.",
  "7.P.AC.3.c": "I can explain how different text types affect how ideas are organized.",
  "7.P.AC.3.d": "I can create and analyze texts that combine different formats and features to communicate with an audience and achieve a purpose.",

  "7.P.CP": "I can work with others and present my ideas clearly for different purposes and audiences.",
  "7.P.CP.1": "I can collaborate with others to complete shared goals and projects.",
  "7.P.CP.1.a": "I can come prepared to participate actively in group discussions and work.",
  "7.P.CP.1.b": "I can help create group rules, set goals, and stay productive when working with others.",
  "7.P.CP.1.c": "I can share my ideas, listen to others, and give helpful feedback.",
  "7.P.CP.1.d": "I can work with others to discuss ideas, answer questions, solve problems, and create texts.",
  "7.P.CP.2": "I can present my ideas in ways that fit my audience and purpose.",
  "7.P.CP.2.a": "I can speak clearly to share ideas, information, and texts.",
  "7.P.CP.2.b": "I can choose the best format or type of presentation for my purpose and audience.",
  "7.P.CP.2.c": "I can adjust my tone, pace, and body language to match my purpose and audience.",
  "7.P.CP.2.d": "I can ask and answer questions to engage with my audience.",
  "7.P.CP.2.e": "I can recite parts of important poems or speeches to build my understanding.",

  "7.L": "I can use grammar, vocabulary, and language rules to help me understand texts and improve my writing.",
  "7.L.GC": "I can understand and use grammar rules and writing conventions to read and write clearly.",
  "7.L.GC.1": "I can use grammar, usage, and mechanics correctly when I read and write.",
  "7.L.GC.1.49": "I can use commas, parentheses, and dashes to add extra information in sentences.",
  "7.L.GC.1.50": "I can use ellipses correctly.",
  "7.L.GC.1.51": "I can use hyphens correctly with prefixes, suffixes, and compound words.",
  "7.L.GC.1.52": "I can use semicolons to connect related ideas in more complex sentences.",
  "7.L.GC.1.53": "I can use parts of speech and phrases or clauses correctly to build clear sentences.",
  "7.L.GC.1.54": "I can use correct punctuation and formatting when adding evidence to my writing.",
  "7.L.GC.1.55": "I can use demonstrative pronouns correctly.",
  "7.L.GC.1.56": "I can use colons to introduce lists, examples, and explanations.",
  "7.L.GC.1.57": "I can use verbals and verbal phrases, such as participles, gerunds, and infinitives, correctly based on their job in a sentence.",
  "7.L.GC.2": "I can use sentence structure to make my writing clear, detailed, and interesting.",
  "7.L.GC.2.a": "I can use sentence structure to better understand and analyze grade-level texts.",
  "7.L.GC.2.b": "I can use different types of sentences to combine ideas and keep verb tense consistent.",
  "7.L.GC.2.c": "I can tell the difference between active and passive voice and revise my writing to keep active voice consistent.",
  "7.L.GC.2.d": "I can add details and descriptions while avoiding misplaced or dangling modifiers.",
  "7.L.GC.2.e": "I will learn this skill in 9th grade.",

  "7.L.V": "I can grow my vocabulary by learning new words, understanding how words work, and using them correctly.",
  "7.L.V.1": "I can build and use vocabulary in everyday, academic, and subject-specific situations.",
  "7.L.V.1.a": "I can learn new words from grade-level texts, digital texts, and other sources.",
  "7.L.V.1.b": "I can use grade-level vocabulary clearly and precisely when speaking and writing.",
  "7.L.V.2": "I can use word knowledge and word analysis skills to figure out and use unfamiliar words.",
  "7.L.V.2.a": "I can break apart words using word origins, Greek and Latin roots, root words, prefixes, and suffixes to understand their meaning.",
  "7.L.V.2.b": "I can use parts of speech to help me understand the meaning of words and phrases.",
  "7.L.V.2.c": "I can build new words using roots and affixes and use them correctly in context.",
  "7.L.V.2.d": "I can choose precise words and phrases by using my knowledge of parts of speech.",
  "7.L.V.3": "I can understand word meanings and choose words carefully to match my purpose.",
  "7.L.V.3.a": "I can continue building this skill through related vocabulary work.",
  "7.L.V.3.b": "I can use relationships between words, phrases, and clauses, such as synonyms, antonyms, analogies, and context clues, to figure out meanings.",
  "7.L.V.3.c": "I can explain how words with similar meanings can have different feelings or tones.",
  "7.L.V.3.d": "I can use dictionaries, digital tools, and other resources to find, check, or clarify word meanings.",
  "7.L.V.3.e": "I can choose the best word or phrase by understanding small differences in meaning.",

  "7.T": "I can learn and grow by reading and working with different types of texts.",
  "7.T.C": "I can understand how context and different influences shape the meaning of texts.",
  "7.T.C.1": "I can analyze how purpose and audience affect texts.",
  "7.T.C.1.a": "I can explain how a text may have more than one purpose and how those purposes target different audiences.",
  "7.T.C.1.b": "I can use text features and modes to help me understand and analyze different types of texts.",
  "7.T.C.1.c": "I can create multimodal texts or presentations for a specific purpose and audience using clear features from different modes.",
  "7.T.C.2": "I can analyze how authors’ or speakers’ perspectives and situations shape texts.",
  "7.T.C.2.a": "I can identify the main perspective in a text and explain how the author supports or sets apart that position.",
  "7.T.C.2.b": "I can analyze how evidence and tone show the author’s perspective and affect credibility.",
  "7.T.C.2.c": "I can analyze how background information and context influence how a text is developed.",
  "7.T.C.2.d": "I can research answers to academic or personal questions using credible sources.",

  "7.T.SS": "I can understand and use structure and style to clearly communicate ideas.",
  "7.T.SS.1": "I can analyze and use text structure to organize ideas and create meaning.",
  "7.T.SS.1.a": "I can analyze how authors change structure or features to match their purpose and audience.",
  "7.T.SS.1.b": "I can use different text structures and features to organize my ideas, share information, and add style.",
  "7.T.SS.1.c": "I can use varied transition words and phrases to connect ideas, sentences, paragraphs, and sections.",
  "7.T.SS.1.d": "I can write organized multi-paragraph texts with a clear introduction, supporting details, and a conclusion.",
  "7.T.SS.2": "I can use language and style to make my writing engaging and effective.",
  "7.T.SS.2.a": "I can explain how figurative language, connotative language, and literary devices affect meaning, mood, or tone.",
  "7.T.SS.2.b": "I can use figurative language, literary devices, or connotative language to create intentional effects for my purpose and audience.",
  "7.T.SS.2.c": "I can decide when to use formal or informal style and apply that choice when writing or speaking.",

  "7.T.T": "I can understand and use different techniques to make meaning when reading and writing.",
  "7.T.T.1": "I can analyze and use narrative techniques to understand and create stories.",
  "7.T.T.1.a": "I can analyze how authors use narrative techniques to develop plot, characters, and setting.",
  "7.T.T.1.b": "I can analyze how plot structure, conflict, and narrative devices like flashback and foreshadowing are used in a text.",
  "7.T.T.1.c": "I can compare and contrast how themes are developed through characters, events, and plot structure.",
  "7.T.T.1.d": "I can compare and contrast a fictional version of a time, place, or character with a historical account of the same period.",
  "7.T.T.1.e": "I can use narrative techniques to improve my writing, engage my audience, and achieve my purpose.",
  "7.T.T.2": "I can analyze and use expository techniques to understand and explain information.",
  "7.T.T.2.a": "I can analyze how informational texts use main ideas, facts, statistics, details, text features, and closure to present information.",
  "7.T.T.2.b": "I can analyze how different authors present the same topic by emphasizing different evidence or interpretations of facts.",
  "7.T.T.2.c": "I learned this skill in an earlier grade.",
  "7.T.T.2.d": "I can use main ideas, facts, statistics, details, text features, and closure to clearly explain information in my writing.",
  "7.T.T.3": "I can analyze and use argumentative techniques to understand and create arguments.",
  "7.T.T.3.a": "I can analyze claims, evidence, counterclaims, and conclusions in arguments.",
  "7.T.T.3.b": "I will learn this skill in 9th grade.",
  "7.T.T.3.c": "I can write arguments using claims, relevant evidence, counterclaims, and logical conclusions.",
  "7.T.T.3.d": "I will learn this skill in 9th grade.",
  "7.T.T.4": "I can analyze and use poetic techniques to understand and create poetry.",
  "7.T.T.4.a": "I can analyze poetic elements like stanzas, rhyme scheme, imagery, figurative language, and sound devices.",
  "7.T.T.4.b": "I can use poetic techniques like stanzas, rhyme, imagery, figurative language, and sound devices to create my own poems.",
 
  "7.T.RA": "I can research, analyze, and use information from texts to learn about topics and support my ideas.",
  "7.T.RA.1": "I can ask questions and conduct research to learn about complex topics.",
  "7.T.RA.1.a": "I can create questions to guide my research and explore connections between complex topics and ideas.",
  "7.T.RA.1.b": "I can find, gather, organize, and combine information from credible sources, including books, websites, and conversations.",
  "7.T.RA.1.c": "I can use what I have learned from research to analyze texts and support, challenge, or extend ideas.",
  "7.T.RA.2": "I can find, evaluate, and use sources and evidence responsibly.",
  "7.T.RA.2.a": "I can find evidence in print and digital sources and record citation information like author, title, website name, page number, and year.",
  "7.T.RA.2.b": "I can analyze sources to decide if they are credible, relevant, and useful for my topic.",
  "7.T.RA.2.c": "I can use a standard citation format to give credit to sources and include each source on a works cited page.",
 
  "7.T.PM": "I can understand how literature reflects different time periods, themes, genres, and styles.",
  "7.T.PM.1": "I can learn about themes, genres, and styles from a specific time period.",
  "7.T.PM.1.a": "I can analyze myths and stories that modern authors have adapted and identify important features of style and theme.",
  "7.T.PM.1.b": "I can analyze a genre of literature from a specific time period and identify important features of style and theme."
},


  practiceSkills: {
    "central-idea": "I can find the central idea or main message of a text.",
    "summarizing": "I can summarize the most important ideas without adding extra details.",
    "details": "I can use important details to understand and explain a text.",
    "text-evidence": "I can choose evidence from the text to support my answer.",
    "claim": "I can identify the main claim or argument an author is making.",
    "reason": "I can identify reasons that support a claim.",
    "evidence": "I can connect evidence to a claim or reason.",
    "argument-structure": "I can understand how claims, reasons, and evidence work together.",
    "author-opinion": "I can identify what the author thinks or believes.",
    "author-meaning": "I can explain what the author means by specific words or ideas.",
    "text-structure": "I can recognize how a text is organized.",
    "cause-effect": "I can explain how one event or idea causes another.",
    "fact-opinion": "I can tell the difference between facts and opinions.",
    "inference": "I can make an inference using clues from the text.",
    "synthesize": "I can combine information from more than one place to form an answer.",
    "critical-thinking": "I can think carefully about ideas and choose the strongest answer.",
    "purpose-audience": "I can explain how a text’s purpose and audience affect the author’s choices.",
    "author-perspective": "I can identify and analyze the author’s perspective in a text.",
    "tone": "I can explain how the author’s tone affects meaning.",
    "credibility": "I can decide whether evidence or a source is trustworthy and relevant.",
    "context": "I can explain how background information or context affects a text.",
    "text-features": "I can use text features to better understand and analyze a text.",
    "multimodal-features": "I can understand how different features, such as images, headings, charts, or layout, add meaning.",
    "figurative-language": "I can explain how figurative language affects meaning.",
    "connotation": "I can explain how word choice creates feelings, tone, or meaning.",
    "mood": "I can explain how a text creates a feeling or mood.",
    "plot-structure": "I can analyze how plot structure shapes a story.",
    "narrative-devices": "I can analyze narrative devices like flashback and foreshadowing.",
    "characterization": "I can analyze how characters are developed through actions, thoughts, dialogue, and events.",
    "theme-development": "I can explain how a theme is developed through characters, events, and plot.",
    "compare-texts": "I can compare and contrast how different texts present similar ideas, themes, or topics.",
    "historical-context": "I can connect a text to the time, place, or historical context it represents.",
    "expository-techniques": "I can analyze how informational texts use facts, statistics, details, and text features.",
    "statistics": "I can understand how statistics support ideas in an informational text.",
    "source-evaluation": "I can evaluate whether a source is credible, relevant, and useful.",
    "word-analysis": "I can use roots, affixes, word parts, and word origins to figure out meaning.",
    "vocabulary-in-context": "I can use context clues to figure out the meaning of words and phrases."
  
  },

  hiddenSkillTags: [
    "mcq",
    "multi-select",
    "matching",
    "highlight",
    "dropdown",
    "drag-drop",
    "video-media",
    "audio-media",
    "passage-1",
    "passage-2",
    "personalization"
  ],

  getOfficialText(code) {
    return this.official[code] || "";
  },

  getStudentText(codeOrSkill) {
    return (
      this.studentFriendly[codeOrSkill] ||
      this.practiceSkills[codeOrSkill] ||
      "I can keep practicing this reading skill."
    );
  },

  shouldShowSkill(skill) {
    return skill && !this.hiddenSkillTags.includes(skill);
  },

formatSkillLabel(skill) {
  if (/^\d+\./.test(skill)) return skill;

  return String(skill)
    .split("-")
    .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
    .join(" ");
}
};