// standards-catalog.js
// Shared standards + skills language for student summaries and teacher dashboard views.

window.RP_STANDARDS_CATALOG = {
official: {
  "8.P": "DOMAIN: Practices (P) Students engage routinely in four literacy practices that ground, shape, and inform the expectations of the Foundations, Language, and Texts domains.",
  "8.P.EICC": "I. BIG IDEA: Engagement & Intention for Comprehension & Composition Students develop personal and academic identities as readers and writers, approaching texts for a variety of tasks and purposes and engaging in reading and writing processes in order to deepen comprehension and strengthen composition.",
  "8.P.EICC.1": "Reader & Writer Identity Build an identity as a reader and writer, developing a repertoire of resources and tools to continuously expand participation as an active consumer and producer of texts.",
  "8.P.EICC.1.a": "Generate, understand, monitor, and discuss personal and academic reading and writing goals, revising as appropriate. (I/C)",
  "8.P.EICC.1.b": "Discuss or write about personal and academic reading and writing preferences, referring to specific techniques, topics, modes, and genres that resonate most. (I/C)",
  "8.P.EICC.1.c": "Select, read, and write texts of personal interest and academic relevance to grade-level texts and topics. (I/C)",
  "8.P.EICC.1.d": "Build a repertoire of comprehension and composition skills, strategies, and techniques, drawing from them as needed to aid the interpretation and construction of texts. (I/C)",
  "8.P.EICC.1.e": "Participate in a community of readers and writers by developing group norms, discussing texts, sharing individual writing, listening as others share their writing, and offering and responding to feedback. (I/C)",
  "8.P.EICC.1.f": "Develop independence and autonomy as a reader and writer. (I/C)",
  "8.P.EICC.2": "Engagement & Intention Engage in written or spoken dialogue as author and audience for a variety of tasks and purposes, making intentional connections within, between, and beyond texts.",
  "8.P.EICC.2.a": "Share real or imagined experiences by interpreting and constructing texts that tell or include stories. (I/C)",
  "8.P.EICC.2.b": "Make use of texts to build knowledge, develop skills, make informed decisions, and share information and ideas. (I/C)",
  "8.P.EICC.2.c": "Explain and learn concepts and processes by interpreting and constructing texts. (I/C)",
  "8.P.EICC.2.d": "Interpret and construct texts to aid the analysis and evaluation of texts and ideas. (I/C)",
  "8.P.EICC.2.e": "Consume and produce texts in order to solve problems or influence decisions. (I/C)",
  "8.P.EICC.3": "Comprehension Strategies Engage with a range of complex texts for a variety of tasks and purposes, accessing and using strategies for comprehension before, during, and after reading as part of the meaning-making process.",
  "8.P.EICC.3.a": "Establish a purpose and set goals for reading, monitor comprehension, and adjust as needed. (I)",
  "8.P.EICC.3.b": "Scan and skim the text, making note of structures and sections that might be most useful. (I)",
  "8.P.EICC.3.c": "Draw from, compare, build, and integrate prior knowledge with the material in the text, addressing inconsistencies or gaps and adding to knowledge repertoires as appropriate. (I)",
  "8.P.EICC.3.d": "Summarize and visualize sections of the text to maintain understanding. (I)",
  "8.P.EICC.3.e": "Make and track predictions about the events and information likely to come next. (I)",
  "8.P.EICC.3.f": "Make, track, and support inferences about different levels of meaning within the text. (I)",
  "8.P.EICC.3.g": "Determine the meanings of unfamiliar words and concepts by applying knowledge of context and of academic vocabulary and word parts. (I)",
  "8.P.EICC.4": "Writing Processes Compose a range of texts for a variety of purposes and audiences, flexibly engaging in writing processes to plan, draft, evaluate, revise, and edit texts.",
  "8.P.EICC.4.a": "Establish a purpose and goals for writing and identify a target audience. (C)",
  "8.P.EICC.4.b": "Plan how to organize the text by selecting modes, genres, and structures that will achieve the purpose and meet the needs of the target audience. (C)",
  "8.P.EICC.4.c": "Generate ideas for content by assessing prior knowledge, gathering information from texts, and engaging in discussions with others. (C)",
  "8.P.EICC.4.d": "Link ideas and information to the organization plan, highlighting ideas and information that are most relevant, useful, and impactful. (C)",
  "8.P.EICC.4.e": "Construct an initial draft by integrating ideas and information; selecting words, phrases, and sentences; and incorporating craft techniques that will best achieve the purpose of the text and resonate with the target audience. (C)",
  "8.P.EICC.4.f": "Evaluate the text’s effectiveness based on self-review or feedback from others, determining whether the text matches the purpose and goals for writing. (C)",
  "8.P.EICC.4.g": "Make changes to the text based on self-evaluation or external feedback, revising the organization, ideas, information, word choices, and craft techniques in order to increase the text’s effectiveness. (C)",
  "8.P.EICC.4.h": "Edit the text, ensuring it adheres to the conventions of written language. (C)",

  "8.P.ST": "II. BIG IDEA: Situating Texts Students develop and apply a multilayered understanding of context, author, audience, and purpose to ground and propel the interpretation and construction of texts.",
  "8.P.ST.1": "Context Develop and apply knowledge of key components of context such as background information, geographic location, cultural influences, time period, and contemporary events when interpreting and constructing texts.",
  "8.P.ST.1.a": "Use prior knowledge, formal or informal research, and discussions with others to identify the key components of context that are most relevant. (I/C)",
  "8.P.ST.1.b": "Consider how context impacts the purposes of the author and the audience. (I/C)",
  "8.P.ST.1.c": "Explore how context shapes the author’s decisions and the audience’s responses during the interpretation and construction of texts. (I/C)",
  "8.P.ST.2": "Author, Audience, & Purpose Interpret and construct texts by developing and applying knowledge of the strategies and techniques authors use to accommodate the target audience and achieve the text’s purpose.",
  "8.P.ST.2.a": "Develop and apply knowledge of author, audience, and context to discern and establish the purpose of texts being interpreted or constructed and to evaluate the extent to which those texts achieve those purposes. (I/C)",
  "8.P.ST.2.b": "Draw from knowledge of author, audience, and context to discern and establish a clear point of view or unique perspective when interpreting and constructing texts. (I/C)",
  "8.P.ST.2.c": "Draw from knowledge of how authors consider context and audience to determine which information and ideas to highlight, which text design is most accessible, which word choices and language structures are most effective, and which craft techniques are most impactful. (I/C)",

  "8.P.AC": "III. BIG IDEA: Author’s Craft Students apply knowledge of author’s craft to enhance the interpretation and construction of texts.",
  "8.P.AC.1": "Reading like a Writer Interpret texts through the author’s lens by identifying, analyzing, and evaluating craft techniques that are connected to the responses, thoughts, decisions, and questions triggered by the text.",
  "8.P.AC.1.a": "Identify, apply, and analyze the literary, expository, and opinion (grades K-5) or rhetorical (grades 6-12) elements in texts, explaining or evaluating how specific elements affect the target audience and support the text’s purpose. (I/C)",
  "8.P.AC.1.b": "Identify, apply, and analyze important, interesting, or effective uses of language, explaining or evaluating how specific word choices affect the target audience and support the text’s purpose. (I/C)",
  "8.P.AC.1.c": "Explain, analyze, and evaluate how the author’s use of sentence structure and syntax affects the target audience and supports the text’s purpose. (I/C)",
  "8.P.AC.1.d": "Describe, analyze, and evaluate the design and organization of the text, explaining how specific formats, structures, patterns, and features influence the audience, contribute to the text’s accessibility, and support the text’s purpose. (I/C)",
  "8.P.AC.2": "Writing like a Reader Construct texts with the audience’s experience in mind, basing decisions about craft techniques on context and purpose.",
  "8.P.AC.2.a": "Integrate literary, expository, and opinion (grades K-5) or rhetorical (grades 6-12) elements to appeal to target audiences and achieve specific purposes. (I/C)",
  "8.P.AC.2.b": "Craft words and phrases in order to influence the responses, thoughts, decisions, and questions of the target audience and achieve a specific purpose. (I/C)",
  "8.P.AC.2.c": "Make decisions about sentence structure and syntax in order to accommodate and influence the audience and achieve a specific purpose. (I/C)",
  "8.P.AC.2.d": "Organize texts by incorporating specific formats, structures, patterns, and features to influence the audience, facilitate accessibility, and support the text’s purpose. (I/C)",
  "8.P.AC.3": "Text Design Consider the impact of text design on audience and purpose when consuming and producing texts across modes and genres.",
  "8.P.AC.3.a": "Explore and create texts in various modes and genres, developing and applying knowledge of how specific features impact meaning, tone, style, purpose, and audience. (I/C)",
  "8.P.AC.3.b": "Apply knowledge of how mode and genre impact what kinds of ideas and information are included in texts. (I/C)",
  "8.P.AC.3.c": "Apply knowledge of how mode and genre impact how ideas and information are structured and arranged in texts. (I/C)",
  "8.P.AC.3.d": "Consume and produce multimodal texts, integrating a variety of genres, text features, and craft techniques to influence target audiences and achieve specific purposes. (I/C)",

  "8.P.CP": "IV. BIG IDEA: Collaboration & Presentation Students build and share knowledge as they engage with others in a range of settings and for a variety of purposes.",
  "8.P.CP.1": "Collaboration Collaborate with others to accomplish shared goals and projects.",
  "8.P.CP.1.a": "Arrive to group discussions and collaborative meetings prepared to be an active participant in the work. (I/C)",
  "8.P.CP.1.b": "Collaborate with others to determine group norms, establish goals and procedures, and facilitate productivity when working on shared projects. (I/C)",
  "8.P.CP.1.c": "Contribute to discussions and shared projects by offering ideas, listening to the ideas of others, and providing feedback. (I/C)",
  "8.P.CP.1.d": "Work with others to discuss topics, investigate questions, solve problems, and explore and create texts. (I/C)",
  "8.P.CP.2": "Presentation Use presentation skills to tailor communication to target audiences for specific purposes.",
  "8.P.CP.2.a": "Communicate clearly to present ideas, information, and texts. (I/C)",
  "8.P.CP.2.b": "Integrate modes and genres most appropriate to purpose and audience. (I/C)",
  "8.P.CP.2.c": "Vary tone, pace, and nonverbal gestures as appropriate to purpose and audience. (I/C)",
  "8.P.CP.2.d": "Engage in dialogue with audiences by asking and answering questions. (I/C)",
  "8.P.CP.2.e": "Build background knowledge by reciting all or part of significant poems and speeches as appropriate by grade level. (I/C)",

  "8.L": "DOMAIN: Language (L) Students learn and apply the structures and conventions of standard English. Students observe and analyze how grammar works in reading and writing. Students build vocabularies and determine word meanings as they relate to reading and writing.",
  "8.L.GC": "I. BIG IDEA: Grammar Conventions Students observe, analyze, and use the structures and conventions of Standard English grammar, usage, and mechanics as they interpret and construct texts.",
  "8.L.GC.1": "Grammar, Usage, & Mechanics Draw from knowledge of the conventions of Standard English grammar, usage, and mechanics when analyzing and constructing texts.",
  "8.L.GC.1.50": "Mechanics: Use ellipses appropriately. (Master)",
  "8.L.GC.1.51": "Mechanics: Use hyphens with appropriate affixes and compound words. (Master)",
  "8.L.GC.1.52": "Mechanics: Use semicolons, with or without a conjunctive adverb, to form compound and compound-complex sentences. (Master)",
  "8.L.GC.1.53": "Grammar, Mechanics Use parts of speech and their associated phrases or clauses to perform indicated sentence functions (e.g., subject, direct object, predicate nominative, modifier). (Master)",
  "8.L.GC.1.54": "Mechanics: Use conventional capitalization, quotation marks, commas, end punctuation, and parentheses (citations) when incorporating textual evidence. (Continue)",
  "8.L.GC.1.56": "Mechanics: Use colons to introduce lists, examples, and explanations. (Master)",
  "8.L.GC.1.57": "Usage: Form and use verbals and verbal phrases (participles/participials, gerunds, and infinitives) based on function. (Continue)",
  "8.L.GC.1.58": "Usage: Use tenses and aspects to indicate the mood of a verb. (Introduce)",
  "8.L.GC.1.59": "Mechanics: Use colons to introduce quotations. (Introduce)",
  "8.L.GC.1.60": "Mechanics: Use dashes appropriately. (Introduce)",
  "8.L.GC.1.61": "Grammar, Usage, Mechanics: Use an appropriate style guide to address complex issues of grammar, usage, or mechanics. (Introduce)",
  "8.L.GC.2": "Syntax Apply understanding of syntax to comprehend, analyze, condense, and combine ideas and information, enhancing clarity, style, and meaning.",
  "8.L.GC.2.a": "Apply understandings of syntax to comprehend and analyze a variety of grade-level texts. (I)",
  "8.L.GC.2.b": "Use a variety of simple, compound, complex, and compound-complex sentences, to condense and combine ideas, maintaining consistent verb tense throughout the text. (C)",
  "8.L.GC.2.c": "Distinguish between active and passive voice, revising texts to maintain consistency in active voice. (C)",
  "8.L.GC.2.d": "Build and enrich ideas and information in texts, integrating modifying phrases and clauses and eliminating misplaced or dangling modifiers to convey meaning and facilitate engagement. (C)",
  "8.L.GC.2.e": "This progression begins in 9th grade.",

  "8.L.V": "II. BIG IDEA: Vocabulary Students engage in a wide range of written and spoken activities during which they expand and deepen their vocabularies, build word analysis skillsets (morphology), and determine or clarify the meanings of words and phrases.",
  "8.L.V.1": "General, Academic, & Specialized Vocabulary Use a variety of approaches to continuously build vocabulary across a range of real-life, academic, and disciplinary contexts and apply those understandings to analyze texts and to communicate effectively.",
  "8.L.V.1.a": "Acquire a range of general, academic, and disciplinary vocabulary through grade-level print, digital, and/or multimodal texts or content. (I)",
  "8.L.V.1.b": "Use grade-level general, academic, and disciplinary vocabulary to communicate clearly and precisely in a variety of settings. (C)",
  "8.L.V.2": "Word Analysis Use word knowledge and word analysis skills to determine the meaning of unfamiliar words and phrases and to communicate effectively for a variety of purposes.",
  "8.L.V.2.a": "Deconstruct words using etymology knowledge, Greek and Latin roots, root words, and/or affixes to determine or clarify meaning in grade-level texts. (I)",
  "8.L.V.2.b": "Apply knowledge of parts of speech to determine the meanings of words and phrases in grade-level texts. (I)",
  "8.L.V.2.c": "Construct words based on knowledge of Greek and Latin roots, root words, and/or affixes and use those words appropriately in context. (C)",
  "8.L.V.2.d": "Use knowledge of parts of speech to determine precise words and phrases when constructing texts. (C)",
  "8.L.V.3": "Meaning & Purpose Analyze the denotative and connotative meanings of words and phrases and strategically apply those understandings when interpreting and constructing texts.",
  "8.L.V.3.a": "This progression transitions to 6-8.L.V.3.b.",
  "8.L.V.3.b": "Analyze relationships between words, phrases, and/or clauses (e.g., synonyms, antonyms, analogies, contextual clues) to determine, distinguish, or clarify the meaning of unknown or multiple-meaning words and phrases. (I)",
  "8.L.V.3.c": "Distinguish between the connotations of words that share a similar denotation (e.g., confident, assertive, egotistic, pompous, smug). (I)",
  "8.L.V.3.d": "Use available print and/or digital resources, including reference materials and digital tools (e.g., online search, embedded word processing features), to determine, clarify, or verify the meaning of unknown or multiple-meaning words and phrases. (I)",
  "8.L.V.3.e": "Determine or clarify the nuanced meanings of closely related words or phrases using available print and/or digital resources to make strategic decisions when speaking and writing. (C)",

  "8.T": "DOMAIN: Texts (T) Students grow in their learning as they purposefully engage with texts.",
  "8.T.C": "I. BIG IDEA: Context Students recognize influences on texts and analyze how they shape meaning.",
  "8.T.C.1": "Purpose & Audience Analyze the impact of purpose and audience on a wide variety of texts.",
  "8.T.C.1.a": "Analyze the development of multiple purposes within a single text and how those purposes target specific audiences. (I)",
  "8.T.C.1.b": "Use text mode features to aid comprehension and analysis of a variety of disciplinary texts and their related contexts. (I)",
  "8.T.C.1.c": "Construct multimodal texts and/or presentations that serve more than one purpose and target a specific audience, using multiple, clearly identifiable features of incorporated modes. (C)",
  "8.T.C.2": "Authors & Speakers Analyze how authors’ and/or speakers’ perspectives influence texts and how circumstances shape their creation.",
  "8.T.C.2.a": "Compare and contrast varying perspectives on a particular topic found across a variety of texts, analyzing how texts establish and develop perspective to shape perceptions or beliefs. (I)",
  "8.T.C.2.b": "Identify an author’s bias and determine how that bias impacts text credibility. (I)",
  "8.T.C.2.c": "Analyze the impact of background information and context (e.g., geography, location, era, historical happenings) on text development. (I)",
  "8.T.C.2.d": "Use a variety of credible sources to research the answers to questions on academic and individual topics of interest. (C)",

  "8.T.SS": "II. BIG IDEA: Structure & Style Students analyze and use organizational structures and style to shape ideas and information.",
  "8.T.SS.1": "Organization Analyze and use organizational structures to craft meaning.",
  "8.T.SS.1.a": "Analyze how authors modify organizational structures or features to convey meaning, respond to the audience, or achieve specific purposes. (I)",
  "8.T.SS.1.b": "Design texts, flexibly employing a variety of text structures and text features to convey information and add style, as appropriate to purpose and audience. (C)",
  "8.T.SS.1.c": "Use varied words, phrases, and clauses to transition between ideas and to aid overall cohesion. (C)",
  "8.T.SS.1.d": "Craft multi-paragraph texts using a coherent structure with an introduction that guides the focus; logically organized and integrated supporting facts, reasons, explanations, details, descriptions, and/or events; and a conclusion with a sense of finality. (C)",
  "8.T.SS.2": "Craft Interpret and use language to craft engaging texts.",
  "8.T.SS.2.a": "Analyze how figurative language, connotative language, and/or literary device choices are used strategically to achieve specific purposes for target audiences. (I)",
  "8.T.SS.2.b": "Use figurative language, literary devices, or connotative language for intentional effects when creating texts to achieve specific purposes or appeal to the target audience. (C)",
  "8.T.SS.2.c": "Use formal or informal style characteristics as indicated by a text’s purpose, audience, and disciplinary context. (C)",

  "8.T.T": "III. BIG IDEA: Techniques Students analyze and apply various techniques to comprehend and shape meaning.",
  "8.T.T.1": "Narrative Techniques Analyze and apply narrative techniques.",
  "8.T.T.1.a": "Analyze how narrative techniques are used across the text to develop plot, characters, and setting. (I)",
  "8.T.T.1.b": "Analyze how plot structures, conflict, and narrative devices (e.g., flashback, foreshadowing) work together to create an intended effect (e.g., suspense, tension, humor) on the audience. (I)",
  "8.T.T.1.c": "Analyze how authors convey and reveal themes through characters, events, and plot structure. (I)",
  "8.T.T.1.d": "Analyze how a modern literary work draws on themes, event patterns, or character types from different time periods. (I)",
  "8.T.T.1.e": "Apply narrative techniques to enhance writing, engage audiences, and achieve specific purposes. (C)",
  "8.T.T.2": "Expository Techniques Analyze and apply expository techniques.",
  "8.T.T.2.a": "Analyze the development of expository techniques used to present and design content, including multiple main ideas, facts, statistics, key details, information from text features, and a sense of closure. (I)",
  "8.T.T.2.b": "Analyze and evaluate how two or more authors writing about the same topic shape their presentations of key information by emphasizing different evidence or advancing different interpretations of facts. (I)",
  "8.T.T.2.c": "This progression ends in 5th grade.",
  "8.T.T.2.d": "Apply multiple expository techniques (e.g., main idea, facts, statistics, key details, text features, sense of closure) to enhance writing and engage audiences. (C)",
  "8.T.T.3": "Argumentative Techniques Analyze and apply argumentative techniques.",
  "8.T.T.3.a": "Analyze the development of argumentative techniques used to present and design content, including an author’s claim, supporting relevant and logical evidence, an identified counterclaim, a rebuttal, and a conclusion that logically follows the argument. (I)",
  "8.T.T.3.b": "This progression begins in 9th grade.",
  "8.T.T.3.c": "Apply argumentative techniques (e.g., author’s claim, supporting relevant and logical evidence, an identified counterclaim, a rebuttal, and a conclusion) to enhance writing and engage audiences. (C)",
  "8.T.T.3.d": "This progression begins in 9th grade.",
  "8.T.T.4": "Poetic Techniques Analyze and apply poetic techniques.",
  "8.T.T.4.a": "Analyze the development of poetic techniques used to present and design content, including stanzas, rhyme scheme, imagery, figurative language, and/or cacophony.",
  "8.T.T.4.b": "Apply poetic techniques (e.g., stanzas, rhyme/rhyme scheme, imagery, figurative language, sound devices) to produce poetry and engage audiences. (C)",

  "8.T.RA": "IV. BIG IDEA: Research & Analysis Students use, discuss, analyze, and curate texts as they engage in various conversations, activities, and projects about a range of grade-level texts and topics.",
  "8.T.RA.1": "Research & Inquiry Conduct research, generating questions to guide investigations of complex topics of interest and using credible sources to support analyses.",
  "8.T.RA.1.a": "Generate questions to guide research and make connections between related topics of interest, formulating questions to investigate complex topics and ideas. (I)",
  "8.T.RA.1.b": "Conduct research by locating, gathering, curating, and integrating information from credible sources (including print, digital, and personal communication) about texts and related topics. (I)",
  "8.T.RA.1.c": "Draw from accumulated knowledge and research to analyze texts, supporting, challenging, or extending ideas and information. (C)",
  "8.T.RA.2": "Curating Sources & Evidence Utilize multiple print and digital texts to address a specific topic or question, assessing source credibility and relevance and integrating evidence properly to avoid plagiarism.",
  "8.T.RA.2.a": "Locate evidence in print, digital, and multimodal sources to support a central idea or question, consulting Modern Language Association (MLA) guidelines to determine the specific information needed to document particular modes and genres. (I)",
  "8.T.RA.2.b": "Analyze print, digital, and multimodal sources for accuracy, credibility, and relevance, determining whether the ideas and information support the topic under investigation and appeal to the target audience. (I)",
  "8.T.RA.2.c": "Follow Modern Language Association (MLA) guidelines when integrating textual evidence, clearly identifying and citing the ideas and information of others and ensuring each source is accompanied by a properly formatted entry on a works cited page. (C)",

  "8.T.PM": "V. BIG IDEA: Periods & Movements Students demonstrate knowledge of dominant themes, genres, and verbal styles of literature from a particular time period.",
  "8.T.PM.1": "Periods & Movements Demonstrate knowledge of dominant themes, genres, and verbal styles of literature from a particular time period.",
  "8.T.PM.1.a": "Read and compare and contrast myths and stories (fictional or historical) that modern writers have adapted into their own works. (I)",
  "8.T.PM.1.b": "Compare and contrast the treatment of a common theme by different writers within a time period. (I)",
},

studentFriendly: {
  "8.P": "I regularly use reading, writing, speaking, listening, and thinking strategies to help me understand texts and create my own writing.",
  "8.P.EICC": "I understand that reading and writing have different purposes, and I use strategies that help me grow as a reader and writer.",
  "8.P.EICC.1": "I see myself as a reader and writer, and I build a collection of tools and strategies that help me understand and create texts.",
  "8.P.EICC.1.a": "I can set reading and writing goals, track my progress, talk about my goals, and revise them when needed.",
  "8.P.EICC.1.b": "I can explain what kinds of reading and writing I prefer and describe the topics, genres, formats, or techniques that connect with me most.",
  "8.P.EICC.1.c": "I can choose, read, and write texts that interest me and connect to 8th grade topics and learning goals.",
  "8.P.EICC.1.d": "I can use a variety of reading and writing strategies to help me understand texts and create stronger writing.",
  "8.P.EICC.1.e": "I can participate respectfully in a reading and writing community by discussing texts, sharing my writing, listening to others, and giving or responding to feedback.",
  "8.P.EICC.1.f": "I can take more ownership of my reading and writing choices, strategies, and progress.",
  "8.P.EICC.2": "I can communicate as both a creator and audience member for different purposes, making thoughtful connections within a text, between texts, and beyond texts.",
  "8.P.EICC.2.a": "I can share real or imagined experiences by understanding and creating texts that tell or include stories.",
  "8.P.EICC.2.b": "I can use texts to learn new information, build skills, make informed decisions, and share ideas.",
  "8.P.EICC.2.c": "I can understand and explain concepts or processes by reading, discussing, and creating texts.",
  "8.P.EICC.2.d": "I can use texts to help me analyze and evaluate ideas and other texts.",
  "8.P.EICC.2.e": "I can use and create texts to solve problems or influence decisions.",
  "8.P.EICC.3": "I can use comprehension strategies before, during, and after reading to help me understand complex texts for different purposes.",
  "8.P.EICC.3.a": "I can set a purpose and goals for reading, check my understanding, and adjust my strategies when needed.",
  "8.P.EICC.3.b": "I can scan and skim a text to notice its structure and identify the sections that may be most useful.",
  "8.P.EICC.3.c": "I can connect what I already know to new information in a text, compare ideas, fix misunderstandings, and build my knowledge.",
  "8.P.EICC.3.d": "I can summarize and visualize parts of a text to help me keep track of meaning.",
  "8.P.EICC.3.e": "I can make and track predictions about what information or events may come next in a text.",
  "8.P.EICC.3.f": "I can make, track, and support inferences about deeper meanings in a text.",
  "8.P.EICC.3.g": "I can figure out unfamiliar words and concepts by using context, academic vocabulary, and word parts.",
  "8.P.EICC.4": "I can write different kinds of texts for different purposes and audiences, using the writing process to plan, draft, evaluate, revise, and edit my work.",
  "8.P.EICC.4.a": "I can decide why I am writing, set writing goals, and identify who my audience is.",
  "8.P.EICC.4.b": "I can plan how to organize my writing by choosing the format, genre, and structure that best fit my purpose and audience.",
  "8.P.EICC.4.c": "I can generate ideas for my writing by thinking about what I already know, gathering information from texts, and discussing ideas with others.",
  "8.P.EICC.4.d": "I can connect ideas and information to my writing plan and choose the details that are most relevant, useful, and powerful.",
  "8.P.EICC.4.e": "I can draft a text by combining ideas and information, choosing effective words and sentences, and using writing techniques that fit my purpose and audience.",
  "8.P.EICC.4.f": "I can evaluate my writing using my own review or feedback from others to decide whether it meets my purpose and goals.",
  "8.P.EICC.4.g": "I can revise my writing based on reflection or feedback by improving the organization, ideas, information, word choice, and writing techniques.",
  "8.P.EICC.4.h": "I can edit my writing to make sure it follows the rules and conventions of written language.",

  "8.P.ST": "I can think about context, author, audience, and purpose to help me understand texts and create my own writing.",
  "8.P.ST.1": "I can use context, such as background information, location, culture, time period, and current events, to better understand and create texts.",
  "8.P.ST.1.a": "I can use what I already know, research, and discussions to identify the parts of context that matter most.",
  "8.P.ST.1.b": "I can explain how context affects the author’s purpose and the audience’s purpose.",
  "8.P.ST.1.c": "I can explore how context influences the author’s choices and the audience’s reactions to a text.",
  "8.P.ST.2": "I can understand and create texts by thinking about the strategies authors use to connect with an audience and achieve a purpose.",
  "8.P.ST.2.a": "I can use knowledge of the author, audience, and context to identify or create a text’s purpose and evaluate how well the text achieves that purpose.",
  "8.P.ST.2.b": "I can use knowledge of the author, audience, and context to identify or create a clear point of view or unique perspective.",
  "8.P.ST.2.c": "I can explain how authors use context and audience to choose what information to emphasize, how to design the text, what words and structures to use, and which craft techniques will have the strongest impact.",

  "8.P.AC": "I can use what I know about author’s craft to better understand texts and create stronger writing.",
  "8.P.AC.1": "I can read like a writer by noticing, analyzing, and evaluating the author’s craft choices and how they affect my thinking, questions, and reactions.",
  "8.P.AC.1.a": "I can identify, use, and analyze literary, expository, and rhetorical elements and explain how they affect the audience and support the author’s purpose.",
  "8.P.AC.1.b": "I can identify, use, and analyze important or effective language choices and explain how specific words affect the audience and support the author’s purpose.",
  "8.P.AC.1.c": "I can explain, analyze, and evaluate how sentence structure and syntax affect the audience and support the author’s purpose.",
  "8.P.AC.1.d": "I can describe, analyze, and evaluate how a text’s design, organization, format, structure, patterns, and features affect the audience, make the text easier to access, and support the author’s purpose.",
  "8.P.AC.2": "I can write with the reader’s experience in mind, making craft choices that fit the context and purpose.",
  "8.P.AC.2.a": "I can use literary, expository, and rhetorical elements to appeal to an audience and achieve a specific purpose.",
  "8.P.AC.2.b": "I can choose words and phrases carefully to influence the audience’s responses, thoughts, decisions, and questions.",
  "8.P.AC.2.c": "I can make choices about sentence structure and syntax to connect with the audience and achieve a specific purpose.",
  "8.P.AC.2.d": "I can organize texts using formats, structures, patterns, and features that influence the audience, make the text easier to understand, and support the purpose.",
  "8.P.AC.3": "I can think about how text design affects the audience and purpose when I read, view, listen to, or create texts in different formats and genres.",
  "8.P.AC.3.a": "I can explore and create texts in different formats and genres, and I can explain how specific features affect meaning, tone, style, purpose, and audience.",
  "8.P.AC.3.b": "I can explain how the format and genre of a text affect what kinds of ideas and information are included.",
  "8.P.AC.3.c": "I can explain how the format and genre of a text affect how ideas and information are organized and arranged.",
  "8.P.AC.3.d": "I can understand and create multimodal texts by combining genres, text features, and craft techniques to influence an audience and achieve a purpose.",

  "8.P.CP": "I can build and share knowledge by working with others in different settings and for different purposes.",
  "8.P.CP.1": "I can collaborate with others to complete shared goals and projects.",
  "8.P.CP.1.a": "I can come prepared to group discussions and collaborative meetings so I can actively participate.",
  "8.P.CP.1.b": "I can work with others to set group norms, goals, and procedures that help the group stay productive.",
  "8.P.CP.1.c": "I can contribute to discussions and projects by sharing ideas, listening to others, and giving feedback.",
  "8.P.CP.1.d": "I can work with others to discuss topics, investigate questions, solve problems, and explore or create texts.",
  "8.P.CP.2": "I can use presentation skills to communicate with a specific audience for a specific purpose.",
  "8.P.CP.2.a": "I can clearly present ideas, information, and texts.",
  "8.P.CP.2.b": "I can choose the formats and genres that best fit my purpose and audience.",
  "8.P.CP.2.c": "I can adjust my tone, pace, and nonverbal gestures to fit my purpose and audience.",
  "8.P.CP.2.d": "I can interact with an audience by asking and answering questions.",
  "8.P.CP.2.e": "I can build background knowledge by reciting important poems or speeches when appropriate.",

  "8.L": "I can use standard English grammar, conventions, and vocabulary to help me understand texts and improve my writing.",
  "8.L.GC": "I can notice, analyze, and use standard English grammar, usage, and mechanics when I read and write.",
  "8.L.GC.1": "I can use what I know about grammar, usage, and mechanics to understand texts and create clear writing.",
  "8.L.GC.1.50": "I can use ellipses correctly.",
  "8.L.GC.1.51": "I can use hyphens correctly with affixes and compound words.",
  "8.L.GC.1.52": "I can use semicolons, with or without conjunctive adverbs, to create compound and compound-complex sentences.",
  "8.L.GC.1.53": "I can identify and use parts of speech, phrases, and clauses to show how words function in a sentence.",
  "8.L.GC.1.54": "I can use correct capitalization, quotation marks, commas, end punctuation, and parentheses when including textual evidence.",
  "8.L.GC.1.56": "I can use colons to introduce lists, examples, and explanations.",
  "8.L.GC.1.57": "I can form and use verbals and verbal phrases, including participles, gerunds, and infinitives, based on their function.",
  "8.L.GC.1.58": "I can use verb tenses and aspects to show the mood of a verb.",
  "8.L.GC.1.59": "I can use colons to introduce quotations.",
  "8.L.GC.1.60": "I can use dashes correctly.",
  "8.L.GC.1.61": "I can use a style guide to solve more complex grammar, usage, and mechanics questions.",
  "8.L.GC.2": "I can use sentence structure to understand, analyze, combine, and strengthen ideas in reading and writing.",
  "8.L.GC.2.a": "I can use my understanding of sentence structure to understand and analyze 8th grade texts.",
  "8.L.GC.2.b": "I can use simple, compound, complex, and compound-complex sentences to combine ideas while keeping verb tense consistent.",
  "8.L.GC.2.c": "I can tell the difference between active and passive voice and revise my writing to keep active voice consistent.",
  "8.L.GC.2.d": "I can strengthen ideas by using modifying phrases and clauses correctly and by removing misplaced or dangling modifiers.",
  "8.L.GC.2.e": "I understand that this skill progression begins in 9th grade.",

  "8.L.V": "I can grow my vocabulary through reading, writing, speaking, and listening, and I can use word-learning strategies to understand and use words and phrases correctly.",
  "8.L.V.1": "I can build vocabulary in real-life, academic, and subject-specific situations and use those words to analyze texts and communicate clearly.",
  "8.L.V.1.a": "I can learn general, academic, and subject-specific vocabulary from 8th grade print, digital, and multimodal texts.",
  "8.L.V.1.b": "I can use general, academic, and subject-specific vocabulary clearly and precisely in different situations.",
  "8.L.V.2": "I can use word knowledge and word analysis skills to figure out unfamiliar words and phrases and communicate effectively for different purposes.",
  "8.L.V.2.a": "I can break apart words using word history, Greek and Latin roots, root words, and affixes to figure out or clarify meaning in 8th grade texts.",
  "8.L.V.2.b": "I can use my knowledge of parts of speech to figure out the meanings of words and phrases in 8th grade texts.",
  "8.L.V.2.c": "I can build words using Greek and Latin roots, root words, and affixes and use those words correctly in context.",
  "8.L.V.2.d": "I can use my knowledge of parts of speech to choose precise words and phrases when I write or speak.",
  "8.L.V.3": "I can analyze the literal and suggested meanings of words and phrases and use that understanding when I read, write, and speak.",
  "8.L.V.3.a": "I understand that this skill progression transitions to 6-8.L.V.3.b.",
  "8.L.V.3.b": "I can analyze relationships between words, phrases, or clauses, such as synonyms, antonyms, analogies, and context clues, to figure out or clarify meaning.",
  "8.L.V.3.c": "I can tell the difference between words that have similar literal meanings but different feelings or associations.",
  "8.L.V.3.d": "I can use print and digital resources to figure out, clarify, or check the meaning of unknown or multiple-meaning words and phrases.",
  "8.L.V.3.e": "I can use print and digital resources to understand small differences in meaning between closely related words or phrases so I can make strong choices when speaking and writing.",

  "8.T": "I can grow as a reader, writer, thinker, and communicator by working purposefully with different kinds of texts.",
  "8.T.C": "I can recognize what influences a text and analyze how those influences shape its meaning.",
  "8.T.C.1": "I can analyze how purpose and audience affect different kinds of texts.",
  "8.T.C.1.a": "I can analyze how a single text develops more than one purpose and how those purposes are aimed at specific audiences.",
  "8.T.C.1.b": "I can use features of different text formats to help me understand and analyze texts from different subjects and contexts.",
  "8.T.C.1.c": "I can create multimodal texts or presentations that have more than one purpose, target a specific audience, and use clear features from different modes.",
  "8.T.C.2": "I can analyze how an author’s or speaker’s perspective influences a text and how circumstances shape why and how the text was created.",
  "8.T.C.2.a": "I can compare and contrast different perspectives on the same topic across multiple texts and analyze how those perspectives shape readers’ perceptions or beliefs.",
  "8.T.C.2.b": "I can identify an author’s bias and explain how that bias affects the credibility of the text.",
  "8.T.C.2.c": "I can analyze how background information and context, such as location, time period, or historical events, affect how a text is developed.",
  "8.T.C.2.d": "I can use several credible sources to research answers to academic questions or questions about topics that interest me.",

  "8.T.SS": "I can analyze and use structure and style to shape ideas and information in texts.",
  "8.T.SS.1": "I can analyze and use organizational structures to create meaning.",
  "8.T.SS.1.a": "I can analyze how authors change text structures or features to create meaning, connect with the audience, or achieve a purpose.",
  "8.T.SS.1.b": "I can design texts using different structures and text features to share information and add style in a way that fits my purpose and audience.",
  "8.T.SS.1.c": "I can use different words, phrases, and clauses to connect ideas and make my writing flow smoothly.",
  "8.T.SS.1.d": "I can write multi-paragraph texts with a clear introduction, logically organized supporting details, and a conclusion that feels complete.",
  "8.T.SS.2": "I can understand and use language choices to create engaging texts.",
  "8.T.SS.2.a": "I can analyze how figurative language, connotative language, and literary devices are used on purpose to affect an audience or achieve a goal.",
  "8.T.SS.2.b": "I can use figurative language, literary devices, or connotative language intentionally to create effects, achieve a purpose, or appeal to an audience.",
  "8.T.SS.2.c": "I can use a formal or informal style based on the text’s purpose, audience, and subject area.",

  "8.T.T": "I can analyze and use different techniques to understand and create meaning in texts.",
  "8.T.T.1": "I can analyze and use narrative techniques.",
  "8.T.T.1.a": "I can analyze how narrative techniques are used throughout a text to develop the plot, characters, and setting.",
  "8.T.T.1.b": "I can analyze how plot structure, conflict, and narrative devices like flashback or foreshadowing work together to create effects such as suspense, tension, or humor.",
  "8.T.T.1.c": "I can analyze how authors reveal themes through characters, events, and plot structure.",
  "8.T.T.1.d": "I can analyze how a modern literary work uses themes, event patterns, or character types from other time periods.",
  "8.T.T.1.e": "I can use narrative techniques to strengthen my writing, engage my audience, and achieve a purpose.",
  "8.T.T.2": "I can analyze and use expository techniques.",
  "8.T.T.2.a": "I can analyze how expository techniques develop information, including main ideas, facts, statistics, key details, text features, and closure.",
  "8.T.T.2.b": "I can analyze and evaluate how two or more authors writing about the same topic present key information differently by emphasizing different evidence or interpreting facts differently.",
  "8.T.T.2.c": "I understand that this skill progression ends in 5th grade.",
  "8.T.T.2.d": "I can use multiple expository techniques, such as main ideas, facts, statistics, key details, text features, and closure, to strengthen my writing and engage my audience.",
  "8.T.T.3": "I can analyze and use argumentative techniques.",
  "8.T.T.3.a": "I can analyze how argumentative techniques develop an argument, including a claim, relevant and logical evidence, a counterclaim, a rebuttal, and a conclusion that follows the argument.",
  "8.T.T.3.b": "I understand that this skill progression begins in 9th grade.",
  "8.T.T.3.c": "I can use argumentative techniques, such as a claim, relevant and logical evidence, a counterclaim, a rebuttal, and a conclusion, to strengthen my writing and engage my audience.",
  "8.T.T.3.d": "I understand that this skill progression begins in 9th grade.",
  "8.T.T.4": "I can analyze and use poetic techniques.",
  "8.T.T.4.a": "I can analyze how poetic techniques develop content, including stanzas, rhyme scheme, imagery, figurative language, and sound choices such as cacophony.",
  "8.T.T.4.b": "I can use poetic techniques, such as stanzas, rhyme, rhyme scheme, imagery, figurative language, and sound devices, to write poetry and engage my audience.",

  "8.T.RA": "I can use, discuss, analyze, and organize texts while working with others on grade-level topics, conversations, activities, and projects.",
  "8.T.RA.1": "I can conduct research by creating questions about complex topics and using credible sources to support my analysis.",
  "8.T.RA.1.a": "I can create research questions, connect related topics, and develop questions that help me investigate complex ideas.",
  "8.T.RA.1.b": "I can conduct research by finding, gathering, organizing, and combining information from credible print, digital, and personal communication sources.",
  "8.T.RA.1.c": "I can use what I know and what I research to analyze texts and support, challenge, or extend ideas and information.",
  "8.T.RA.2": "I can use multiple print and digital sources to answer a question or explore a topic, checking credibility and relevance and using evidence correctly.",
  "8.T.RA.2.a": "I can find evidence in print, digital, and multimodal sources to support a central idea or question and use MLA guidelines to know what source information I need.",
  "8.T.RA.2.b": "I can analyze sources for accuracy, credibility, and relevance and decide whether their information supports my topic and appeals to my audience.",
  "8.T.RA.2.c": "I can follow MLA guidelines when using textual evidence by clearly citing others’ ideas and including properly formatted works cited entries.",

  "8.T.PM": "I can understand major themes, genres, and writing styles from literature in a specific time period.",
  "8.T.PM.1": "I can show knowledge of major themes, genres, and writing styles from literature in a specific time period.",
  "8.T.PM.1.a": "I can read, compare, and contrast myths and stories that modern writers have adapted into their own works.",
  "8.T.PM.1.b": "I can compare and contrast how different writers from the same time period treat a common theme."
},


practiceSkills: {
  "reading-goals": "I can set a purpose for reading, monitor my understanding, and adjust my strategies when needed.",
  "writing-goals": "I can set a purpose for writing, identify my audience, and use goals to guide my work.",
  "reader-writer-identity": "I can build independence as a reader and writer by choosing strategies, tools, and texts that help me grow.",
  "comprehension-strategies": "I can use strategies before, during, and after reading to understand complex texts.",
  "summarizing": "I can summarize the most important ideas or events without adding extra details.",
  "visualizing": "I can picture ideas, events, or information in a text to help me understand meaning.",
  "prediction": "I can make and track predictions using clues from the text.",
  "inference": "I can make and support inferences about deeper meanings in a text.",
  "central-idea": "I can determine central ideas or main messages and explain how they develop.",
  "details": "I can use important details to understand, explain, or analyze a text.",
  "text-evidence": "I can choose strong evidence from a text to support my answer or analysis.",
  "synthesize": "I can combine information from more than one part of a text or from multiple texts to form a stronger answer.",
  "critical-thinking": "I can analyze ideas carefully and choose the strongest answer based on evidence.",
  "context": "I can explain how background information, culture, time period, location, or events affect a text.",
  "historical-context": "I can connect a text to the time, place, events, or historical context it represents.",
  "purpose-audience": "I can analyze how a text’s purpose and audience affect the author’s choices.",
  "multiple-purposes": "I can analyze how one text can develop more than one purpose for specific audiences.",
  "author-perspective": "I can identify and analyze an author’s or speaker’s perspective.",
  "author-bias": "I can identify an author’s bias and explain how it affects the credibility of a text.",
  "credibility": "I can decide whether a source or piece of evidence is accurate, trustworthy, relevant, and useful.",
  "author-meaning": "I can explain what an author means through specific words, ideas, or craft choices.",
  "author-craft": "I can analyze how an author’s craft choices affect meaning, audience, and purpose.",
  "rhetorical-elements": "I can analyze how rhetorical elements support an author’s purpose and affect the audience.",
  "word-choice": "I can analyze how specific words and phrases affect meaning, tone, purpose, and audience.",
  "tone": "I can explain how an author’s tone affects the meaning or impact of a text.",
  "connotation": "I can explain how word choice creates feelings, associations, tone, or meaning.",
  "figurative-language": "I can analyze how figurative language affects meaning and supports an author’s purpose.",
  "literary-devices": "I can analyze how literary devices create effects and support meaning.",
  "sentence-structure": "I can analyze how sentence structure and syntax affect meaning, style, audience, and purpose.",
  "syntax": "I can use sentence structure to understand, analyze, combine, and strengthen ideas.",
  "active-passive-voice": "I can distinguish between active and passive voice and explain how voice affects clarity and style.",
  "modifiers": "I can recognize how modifying phrases and clauses add detail and how misplaced modifiers can confuse meaning.",
  "grammar-mechanics": "I can apply grammar, usage, mechanics, and style rules when reading and writing.",
  "punctuation": "I can understand how punctuation such as semicolons, colons, ellipses, dashes, hyphens, and quotation marks affects meaning.",
  "word-analysis": "I can use roots, affixes, word parts, and word origins to figure out word meanings.",
  "vocabulary-in-context": "I can use context clues and word relationships to determine or clarify word meanings.",
  "academic-vocabulary": "I can understand and use academic and subject-specific vocabulary clearly and precisely.",
  "denotation-connotation": "I can distinguish between literal meanings and suggested meanings of words and phrases.",
  "text-structure": "I can analyze how a text is organized and how that structure shapes meaning.",
  "organization": "I can analyze how authors organize ideas, information, events, or arguments to achieve a purpose.",
  "transitions-cohesion": "I can explain how transitions and connections help ideas flow together clearly.",
  "text-features": "I can use text features to better understand and analyze a text.",
  "text-design": "I can analyze how format, structure, layout, and design choices affect meaning, audience, and purpose.",
  "mode-genre": "I can explain how a text’s mode or genre affects what information is included and how it is presented.",
  "multimodal-features": "I can analyze how features such as images, audio, video, headings, charts, captions, or layout add meaning.",
  "compare-texts": "I can compare and contrast how different texts present similar ideas, topics, themes, or perspectives.",
  "paired-text-analysis": "I can analyze how two or more texts on the same topic emphasize different evidence, ideas, or interpretations.",
  "source-comparison": "I can compare sources to determine how each one presents information or supports an idea.",
  "narrative-techniques": "I can analyze how narrative techniques develop plot, characters, setting, and meaning.",
  "plot-structure": "I can analyze how plot structure shapes a story and affects the audience.",
  "conflict": "I can analyze how conflict develops and contributes to meaning in a narrative.",
  "narrative-devices": "I can analyze how narrative devices like flashback and foreshadowing create effects such as suspense, tension, or humor.",
  "characterization": "I can analyze how characters are developed through actions, thoughts, dialogue, relationships, and events.",
  "theme-development": "I can analyze how a theme is developed through characters, events, plot structure, and conflict.",
  "modern-adaptation": "I can analyze how a modern work draws on themes, events, or character types from earlier stories or time periods.",
  "expository-techniques": "I can analyze how informational texts use main ideas, facts, statistics, details, text features, and closure.",
  "statistics": "I can explain how statistics support ideas in an informational text.",
  "claim": "I can identify the main claim or argument an author is making.",
  "reason": "I can identify reasons that support a claim.",
  "evidence": "I can connect evidence to a claim, reason, central idea, or analysis.",
  "counterclaim": "I can identify a counterclaim and explain how it relates to an argument.",
  "rebuttal": "I can analyze how a rebuttal responds to a counterclaim.",
  "argument-structure": "I can analyze how claims, reasons, evidence, counterclaims, rebuttals, and conclusions work together.",
  "poetic-techniques": "I can analyze how poetic techniques such as stanzas, rhyme, imagery, figurative language, and sound devices create meaning.",
  "imagery": "I can analyze how imagery helps create meaning, tone, mood, or effect.",
  "sound-devices": "I can analyze how sound devices affect the meaning or impact of a poem.",
  "research-questions": "I can create research questions that guide investigation of complex topics and ideas.",
  "research": "I can locate, gather, organize, and combine information from credible sources.",
  "source-evaluation": "I can evaluate whether a source is accurate, credible, relevant, and useful for my purpose.",
  "mla-citation": "I can use MLA guidelines to cite evidence and document sources correctly.",
  "evidence-integration": "I can integrate evidence from sources clearly while giving credit to the original source.",
  "periods-movements": "I can analyze themes, genres, and writing styles from literature in a specific time period.",
  "common-theme": "I can compare how different writers from the same time period treat a common theme.",
  "collaboration": "I can participate in discussions and shared work by listening, contributing ideas, and responding to feedback.",
  "presentation": "I can present ideas clearly in a way that fits my purpose and audience."
},

  hiddenSkillTags: [
    "mcq",
    "multi-select",
    "matching",
    "highlight",
    "dropdown",
    "drag-drop",
    "video-media",
    "audio-media",
    "passage-1",
    "passage-2",
    "personalization"
  ],

  getOfficialText(code) {
    return this.official[code] || "";
  },

  getStudentText(codeOrSkill) {
    return (
      this.studentFriendly[codeOrSkill] ||
      this.practiceSkills[codeOrSkill] ||
      "I can keep practicing this reading skill."
    );
  },

  shouldShowSkill(skill) {
    return skill && !this.hiddenSkillTags.includes(skill);
  },

formatSkillLabel(skill) {
  if (/^\d+\./.test(skill)) return skill;

  return String(skill)
    .split("-")
    .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
    .join(" ");
}
};